### ISSUE TITLE
High performance mario kart on ruby

### ISSUE THREAD

**Issue by mtcmorris** [rails-oceania/melbourne-ruby#100]
"We have a serious workplace with a serious problem - Mario Kart. We’ve employed Ruby to answer the important questions - just who is the best and is there any hope for justice in kart?"

## What

I gave a talk at [Rubyconf 2018](https://www.rubyconf.org.au/2018/speakers) about a system we've developed at Ferocia using Ruby (& Mario Kart).  Would love to give it to roromelb as many people couldn't make it up to Sydney.  It covers a fairly unorthodox use of ruby (& demo) for both beginners and veterans.

**Comment by tcn33** [comment]
@mtcmorris Yes please! How about May 30th?

**Comment by mtcmorris** [comment]
🔒 it in

**Comment by mtcmorris** [comment]
Yep yep.  I'll be there.  Will bring my setup too if that's ok 😬

**Comment by tcn33** [comment]
Absolutely. We'll have your talk up second during the pizza break so that you've got time to set up. Sound good?
