### ISSUE TITLE
Breaking builds & breaking bones

### ISSUE THREAD

**Issue by SelenaSmall** [rails-oceania/melbourne-ruby#102]
Personal story about getting into tech late in a non-traditional fashion

**Comment by radar** [comment]
Hey Selena, I think we talked on Wednesday about you talking in June. Are you still keen to do that?

**Comment by SelenaSmall** [comment]
Hey Ryan!

Yes, I’m still keen to do it June. I’m pretty confident I’ll be ready by then but just in case, can we touch base in two weeks to see how I’m tracking?

Thanks
Selena Small

**Comment by tcn33** [comment]
@SelenaSmall still good for next week?

**Comment by SelenaSmall** [comment]
Hey Toby!

Yes, I’m all organised 😃
Also mentioned to Ryan that I wouldn’t mind going first. The talk is around 30 minute but feedback so far is that it’s interesting... hope that’s going to be okay 👌 

Selena Small

**Comment by fbvilela** [comment]
https://youtu.be/7bTXuIBhwGI
