### ISSUE TITLE
VI everywhere - what's your super power

### ISSUE THREAD

**Issue by saramic** [rails-oceania/melbourne-ruby#103]
As a malleable beginner programmer back in the 90's I took some advice to set my command line to vi mode `set -o vi`. As I continued through uni and onto my first job I couldn't touch type but when I was on the command line I was faster then most - I had a super power, every keystroke had the power of vi!

In this talk I explore

* common patterns for using vi on the command line
* vi everywhere: in the browser, db console, rails console even as input to ruby programs
* My list of essential vi commands is relatively short
* _Dojo_ - how to make the most of someone's advice - practice it - habitual learning

**Comment by tcn33** [comment]
@saramic Still good for next week?

**Comment by saramic** [comment]
Stressed but yeah all good will be ready 

Cheers

**Comment by fbvilela** [comment]
https://youtu.be/l6dwu6cCfkM
