### ISSUE TITLE
Fantastic passwords and where to find them

### ISSUE THREAD

**Issue by philnash** [rails-oceania/melbourne-ruby#104]
The humble password is broken. The internet is littered with poor security practices and password breaches, but the world is not ready to go password free yet. So what can we do to protect our users?

Let's take a look at how we currently protect passwords, at what we can throw away from those processes and what we can bring in to strengthen our users' passwords. Together we can move the world from "password1" to "correct horse battery staple" and beyond!

**Comment by tcn33** [comment]
@philnash how's August looking?

**Comment by philnash** [comment]
@tcn33 Yes, good. If you've got space in the line up then I'm in!

**Comment by tcn33** [comment]
@philnash actually could we push to September? Sorry :/

**Comment by philnash** [comment]
Will that be the 26th?

**Comment by tcn33** [comment]
Yes, sorry.

**Comment by tcn33** [comment]
@philnash double-checking, are you still available now that we've had to move RORO to Oct 3?

**Comment by philnash** [comment]
It appears that I am available. 👍

**Comment by philnash** [comment]
Totally available and ready to go 👍

**Comment by tcn33** [comment]
https://www.youtube.com/watch?v=fu8zxwr7kNk
