### ISSUE TITLE
Building a Gem with native extensions

### ISSUE THREAD

**Issue by tristanpenman** [rails-oceania/melbourne-ruby#105]
There are many reasons you might want to write a Gem using native extensions, e.g:
* Performance - CPU heavy tasks, such as number crunching, can be written in C, to be many times faster than the equivalent Ruby code. For the daring among us, you can use multiple threads, GPUs, etc.
* Re-using existing code - whether it be legacy code that is essential to your business, or a third party library that does exactly what you need, a native extension can give you access to that functionality from Ruby.

[RMagick](https://github.com/rmagick) is a great example here.

Whatever your reasons, the motivation for this talk is _because you can!_

For this talk, my plan is to demonstrate how, using native extensions and a C library called [libclipboard](https://github.com/jtanx/libclipboard), we can access a user's clipboard from Ruby code.

**Comment by tcn33** [comment]
@tristanpenman looks good! Two questions: how long do you see this talk running, and are you free August 29th? 😄

**Comment by tristanpenman** [comment]
I can do the 29th!

This is the sequence of topics that I had in mind:
* Structure of a gem (3-5 mins)
* Extending Ruby using C, and how that works (10 mins)
* How to include that C code in a Gem (5 mins)
* Gotchas (3 mins)

So I would hope to have the planned content done in under 25 mins, leaving about 5 minutes for questions.

**Comment by tcn33** [comment]
@fbvilela how'd the video go for August's meetup?

**Comment by fbvilela** [comment]
Man, the August recordings didn't work... it didn't record :(

**Comment by tcn33** [comment]
https://www.youtube.com/watch?v=O9GjC5oh0o0

**Comment by tcn33** [comment]
@fbvilela August looks fine from here, all good 👍
