### ISSUE TITLE
Rails 5.1 system specs

### ISSUE THREAD

**Issue by elle** [rails-oceania/melbourne-ruby#106]
In Rails 5.1, a new kind of test was added, called system test. These tests wrap capybara and Rails to allow for a full stack testing experience from frontend javascript all the way down to your database.
Shall we find out what that means?

**Comment by tcn33** [comment]
hey @elle, are you available to give this talk on the 31st?

**Comment by tcn33** [comment]
@elle still available to do this one, perhaps April 24th?
