### ISSUE TITLE
What are blocks?

### ISSUE THREAD

**Issue by tomdalling** [rails-oceania/melbourne-ruby#107]
Everyone who learns Ruby, at some point in their studies, asks: what are blocks? This is one of the most common questions asked by beginners.

This is a lightning talk, running at a little over 5 minutes, and is aimed at beginners.

## Outline

- Syntax
- Blocks are functions, just like methods
- Blocks can be converted into methods, and vice versa
- Blocks are different to methods, in that they are:
  - Anonymous
  - Nested
  - Closures
  - Arguments to method calls
- Summary
- Plug Hack Night meetup

**Comment by tomdalling** [comment]
Done.

**Comment by tcn33** [comment]
https://www.youtube.com/watch?v=HR8iA4Hk1Ck
