### ISSUE TITLE
Applied event sourcing

### ISSUE THREAD

**Issue by ZimbiX** [rails-oceania/melbourne-ruby#109]
Event sourcing has been discussed a few times at Melbourne Ruby / Ruby Conf AU, but still I feel the specifics are not well known regarding how to actually go about it. There are not yet many tools to facilitate this, especially in Ruby.

I've been at GreenSync for 14 months as part of a small team producing [deX](https://dex.energy) (distributed energy exchange) using event sourcing. The core components of deX are finally in production, and I'd like to impart our method and learnings that got us to where we are today.

**Comment by tcn33** [comment]
@ZimbiX Looks good! Are you available to give this one in September?

**Comment by tcn33** [comment]
@ZimbiX double-checking, are you still available now that we've had to move RORO to Oct 3?

**Comment by ZimbiX** [comment]
Ah ok. Still good

**Comment by radar** [comment]
Just double-extra-special-checking: you're still available for this Wednesday night?

**Comment by ZimbiX** [comment]
@radar indeed I am :D

**Comment by tcn33** [comment]
@fbvilela and how about September/early October? 😁

**Comment by fbvilela** [comment]
The talks are up :)

**Comment by tcn33** [comment]
https://www.youtube.com/watch?v=KOfG3BK2Ue8
