### ISSUE TITLE
Mind mapping for clarity

### ISSUE THREAD

**Issue by erinbelot** [rails-oceania/melbourne-ruby#110]
Proposal
5 minute talk lightening talk
Beginners
September/October

Hi there! 
I'd like to propose a talk based on mind mapping. I found for me having a place to visualise all the data has really pushed me further along in my programming. Having somewhere that forces you to collate all the concepts that you need to having a working knowledge of a subject, and then have that mapped out for you - it really helps see your weak points and where you need to improve.

<img width="553" alt="screen shot 2018-09-05 at 5 08 34 pm" src="https://user-images.githubusercontent.com/36493925/45076679-5d7ec080-b12e-11e8-933e-2f68f2e6fb4a.png">

This would be only my second tech talk so please let me know if there's anything I could do improve the talk idea. It's really helped me, so I was hoping it would help other people starting out and seniors alike.

Thankyou!
Erin

**Comment by tcn33** [comment]
Hey @erinbelot, are you available to do this one on the 31st?

**Comment by erinbelot** [comment]
Hey @tcn33, I'm actually pretty chockers this week. Is it okay if I'm a part of the next one instead?

**Comment by tcn33** [comment]
Hey @erinbelot could we move this one to January please? We're going to make that one all lightning talks, with an optional rehearsal night.

**Comment by tcn33** [comment]
Hey @erinbelot! Just wanted to check if you would you like to do a rehearsal, and if so when would be good for you?

**Comment by erinbelot** [comment]
Hey @tcn33! I had my appendix out a week or so back, so I'm not really up to heading into the city right now. But maybe we could do something over skype? Or in a week or so?

**Comment by oheydrew** [comment]
*stalks* Ow! Sounds painful. Get well soon @erinbelot !

**Comment by tcn33** [comment]
Ouch! Hope you feel better soon!

How about the week beforehand - around the 23rd?

**Comment by erinbelot** [comment]
That perfect! Thank you :)

**Comment by tcn33** [comment]
@erinbelot are you able to make part/all of 1pm to 2:50pm on Wednesday Jan 23rd at Culture Amp for rehearsal?

**Comment by erinbelot** [comment]
Hey @tcn33, yep that should be fine.

**Comment by tcn33** [comment]
Let's meet in the lobby at 31 Queen St at 1pm on Wednesday. Cool?

**Comment by tcn33** [comment]
All good! I hope you feel better soon.

**Comment by radar** [comment]
Hi @erinbelot, would you like to give this talk at either _next week's_ Melbourne Ruby meetup, or perhaps the May one?

**Comment by erinbelot** [comment]
@radar Alrighty :)

**Comment by erinbelot** [comment]
Next week is good if you have spots to fill, otherwise May works too

**Comment by radar** [comment]
Hey @erinbelot, it would be great if you could come along tomorrow night and speak :) Are you still free?

**Comment by erinbelot** [comment]
Yeah that should be fine :)

**Comment by pat** [comment]
Hi Erin - just a quick note to let you know I'm hosting the meet tonight, as Ryan and Toby can't make it - so feel free to find me before the proceedings kick off, we can check your laptop setup.
