### ISSUE TITLE
Multi layer outside in behavioural driven testing

### ISSUE THREAD

**Issue by saramic** [rails-oceania/melbourne-ruby#111]
An opinionated perspective on how to BDD with RSpec from feature level "lifecycle flows" and "page mechanics", unit testing controllers and everything in between on a demo rails app with a customer facing SPA (Single Page App - in ReactJS or Ember).

Should have more info soon

Ready for November 2018 meetup

joint presentation @selenasmall (Selena Small) and @saramic (Michael Milewski)

**Comment by radar** [comment]
@saramic Sounds good. Want to do this one for the November meetup?

**Comment by saramic** [comment]
@radar yep let's do it - @SelenaSmall and @saramic should be ready for November - I presume that is post rails camp 23-26 Nov ie on Wednesday 28th November - it will be longish ~30 - 40 mins

**Comment by saramic** [comment]
@radar all good for Halloween Wed 31 October let's do this!

**Comment by fbvilela** [comment]
https://www.youtube.com/watch?v=p72EPNXbjiU&feature=youtu.be
