### ISSUE TITLE
Testing Ruby Microservices - A War Story

### ISSUE THREAD

**Issue by korobochek** [rails-oceania/melbourne-ruby#112]
This is a talk about the Journey we have undertaken for testing Ruby (micro)services at REA. What we have tried, what worked, what did not work. It will cover pros and cons of the following levels of testing:
- unit tests in Ruby
- integration tests within a Ruby microservice
- integration tests between microservices
- pact tests
- synthetic transactions

In this talk I will outline what combinations of each test category we have used previously and why. Why did we decide to change from one test strategy to another. And I will finish off with what testing strategy we ended up with. 

The idea of this talk is to depict that there is no one solution that fits all and even within the same business domain and architecture.

If you have further questions regarding the talk content - please let me know 😄

**Comment by korobochek** [comment]
@tcn Hehe - that was quick! I am thinking it would be no more that 30 mins long and I think that every level would benefit from it. 

The idea is to provide a quick explanation of what each test category is and go into our experience with each of those. I am planning to have it fairly high level to convey the concepts and thinking behind choosing/changing test strategies rather than to dictate how to do things or show code examples 😃

**Comment by tcn33** [comment]
Sounds good! Looks like November 28th at this point, though we may have a slot open this month (the 31st) if you're good to go already.

**Comment by korobochek** [comment]
28th of November sounds great! :) I do not believe I would be ready by the 31st of October though.

**Comment by tcn33** [comment]
@korobochek Still good for 28/11?

**Comment by korobochek** [comment]
Yep, still good :)

**Comment by tcn33** [comment]
@fbvilela ty!
