### ISSUE TITLE
Ruby Newbies: "Arguing With Ruby: A breakdown of Ruby Method Arguments"

### ISSUE THREAD

**Issue by oheydrew** [rails-oceania/melbourne-ruby#113]
### The WhatWhereWhenHow

**When**: November (Ruby Newbies?)
**Length**: 5-10min (Lightning talk)
**Intended Audience**: Beginners, mostly 
**Twitter Username**: [@oheydrew](http://www.twitter.com/oheydrew) 
**Picture Link**: [dat me](http://www.oheydrew.me/avatar/avatar-drew_noll-10_18.png)

This will be my first talk, so I wanted to scope it to something specific and short in order to keep it to time and not get too carried away. 

### The Lowdown

Ruby is *super* flexible when it comes to providing arguments to it's methods. So much so, that it can get mighty overwhelming for the beginner. `key: value` pairs inside method definitions? default argument values? and "keyword arguments"? *What the heck is a `**args`, anyway?* - In this talk, I hope to demystify some of the "magic" behind how we define, and call our methods inside the ruby syntax- Starting small with Positional Arguments, all the way up to that crazy, cool-yet-initially-confusing "Seattle Style" bracket-less code we see all throughout Rails. 

Oh. And Pirate puns. Because Pirates, love `ARGS`.

**Comment by tcn33** [comment]
November! Yeah?

**Comment by oheydrew** [comment]
Yeah! I hope I'm not the only one though! :joy:

**Comment by tcn33** [comment]
Hey Drew,

Ruby Newbies is looking like January at the moment. Okay to move yours to there? That'll give us time to do one or more rehearsal nights.

**Comment by oheydrew** [comment]
Awesome. Yeah, that's fine. I'll see if I can have it ready by railscamp, maybe I can do a practice run then. Or maybe it will become my railscamp project 😂

**Comment by tcn33** [comment]
Hey @oheydrew! Just wanted to check if you would you like to do a rehearsal, and if so when would be good for you?

**Comment by oheydrew** [comment]
Also, on the topic of the talk, how long do you think it should be? I was
aiming for 5 minutes for a super “lightning” talk, but I’m thinking it
might be more comfortable at 7 or even 10? Would it be awful it I tacked on
a few minutes?

I can write a compressed version, can any intro fluffiness, but I do like
the idea of a little setup and being able to pace it. :)


On January 3, 2019 at 7:26:33 PM, Drew Noll (drew@oheydrew.me) wrote:

Heya Tobes! Hope the xmas break did you well.

Re: The talk, yeah, I guess a rehearsal wouldn’t hurt. I’m still not 100%
finished writing it (because I am slack and put it off like a champ 😅) but
perhaps… How about a week / few days beforehand? Is anyone else doing a
rehearsal? Are you organizing a group rehearsal night?


On January 3, 2019 at 2:19:52 PM, Toby Nieboer (notifications@github.com)
wrote:

Hey @oheydrew <https://github.com/oheydrew>! Just wanted to check if you
would you like to do a rehearsal, and if so when would be good for you?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rails-oceania/melbourne-ruby/issues/113#issuecomment-451047492>,
or mute the thread

**Comment by tcn33** [comment]
If everyone is comfortable with a group rehearsal night that would make things easy 😄 Perhaps @radar can hook us up with some space at CA?

Anywhere between 5 and 15 minutes is perfect.

**Comment by oheydrew** [comment]
👍 Nice. I'll probably go a little over 5 then :P

**Comment by tcn33** [comment]
@oheydrew are you able to make part/all of 1pm to 2:50pm on Wednesday Jan 23rd at Culture Amp for rehearsal?

**Comment by oheydrew** [comment]
I can likely make that work. Probably closer to 1pm though :)

**Comment by tcn33** [comment]
Let's meet in the lobby at 31 Queen St at 1pm on Wednesday. Cool?

**Comment by oheydrew** [comment]
Perfect 👌

**Comment by fbvilela** [comment]
https://youtu.be/me8CK_4TPpo

**Comment by oheydrew** [comment]
Thanks! :D Amazing :) So good to see how I did :)
