### ISSUE TITLE
Know Thy App

### ISSUE THREAD

**Issue by lachie** [rails-oceania/melbourne-ruby#114]
I'd like to give a talk about getting to know your app (ultimately via functional & load testing).
The main thrust is to encourage thinking of apps in global terms to promote an in-depth knowledge and intuition of all the parts of apps (code and stack) by using different tools to explore it.

What is the goal of your app? Business & tech goals.
Especially as a newly minted junior, how do you get to know the app in depth? Empirical methods like load testing can help explore this.
Load & functional testing helps develop a realistic, intuitive-but-evidence-based feel for how an app runs, and thus the relative importance of its components and their interconnection.
it also helps in thinking clearly about the trade-offs your app can make - e.g. is it more important to be fast or correct? Why?
Although load testing is an empirical or forensic approach that applies to all sorts of apps, I think its a particularly good fit for Rails apps given the performance vs productivity trade-off that Rails offers.

Full disclosure: I work for flood.io & will incidentally mention flood.io as a good tool for easily getting in to load testing :)

Intended audience: load testing beginners, developers of all ages

I'd like to present at the November 28th meetup
I'm giving this same talk at roro sydney tonight (13/11), and its tuned for 15mins. If there are 20min slots that'd be perfect -- I can talk slower/comfortably.

it me:
@lachiecox on the tweeter

thanks!
Lachie

**Comment by tcn33** [comment]
@fbvilela How did the video turn out from November?

**Comment by fbvilela** [comment]
here we go :) https://youtu.be/z0pfFSNIVJc

**Comment by tcn33** [comment]
@fbvilela thank you!
