### ISSUE TITLE
Refactoring in Ruby - Or how I learned to love pure functions

### ISSUE THREAD

**Issue by davich** [rails-oceania/melbourne-ruby#115]
After 15 years of professional coding, I realise that refactoring is one of the most important skills. 
 
This is a beginner to intermediate level talk about:
- Refactoring your ruby code into small, single purpose methods. 
- Using tests as a safety net
- When and how to split out a new class
- Using pure functions for ease of testing and maintainability

Hoping to do this early next year. Thanks

**Comment by tcn33** [comment]
Nice! We're doing Ruby Newbies in Jan, so how's Feb?

**Comment by davich** [comment]
Perfect! Thanks Toby!

**Comment by fbvilela** [comment]
https://youtu.be/HzxHBgsrBVY
