### ISSUE TITLE
Ruby Magic Tricks

### ISSUE THREAD

**Issue by radar** [rails-oceania/melbourne-ruby#116]
Sleight of hand is an acquired skill. Making people believe certain things are true when they're not, is easy to do in the physical world. I'm a shitty physical world magician, but a real code magician.

I will bend the laws of mathematics, make things seem true when they shouldn't be, bring JavaScript-style (aka the right way) sorting to Ruby, and much more!

**Comment by tcn33** [comment]
How long?

**Comment by radar** [comment]
15-20 minutes.

**Comment by fbvilela** [comment]
https://youtu.be/lSiD3LZanPI
