### ISSUE TITLE
Remote Working - Why You Should (Or Shouldn't) Embrace It

### ISSUE THREAD

**Issue by tcn33** [rails-oceania/melbourne-ruby#117]
Good software engineers can be found anywhere, and embracing remote working enables you to tap into that global pool. But just because you *can*... does that mean you *should*? In this talk I'll go through some dos and don'ts, talk about some pitfalls, and hopefully guide you towards doing remote the right way.

**Comment by VanessaNimmo** [comment]
https://www.youtube.com/watch?v=P01gclPahxo
