### ISSUE TITLE
Ruby Newbies: Unpacking Rails Helper Magic

### ISSUE THREAD

**Issue by VanessaNimmo** [rails-oceania/melbourne-ruby#118]
# Ruby Newbies: Unpacking Rails Helper Magic

*Length:* Lightning talk - 5-10 mins

*Intended Audience:* Beginners

*Twitter Username:* [@nessnimmo](@nessnimmo)

**Details**

Rails Magic is pretty magical, but what happens when you need to pull back the curtain and find out what's underneath? In this talk, I'll follow the Ruby path from several of my confusingly-broken-Rails-project moments to investigate the wonderful helper methods that are getting the job done in the background.

**Comment by tcn33** [comment]
Hey @VanessaNimmo! Just wanted to check if you would you like to do a rehearsal, and if so when would be good for you?

**Comment by VanessaNimmo** [comment]
Hi Toby! Yes please to a rehearsal - is the week before a good time? I'm free the previous Wednesday evening (and also most evenings).


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by tcn33** [comment]
Sounds good! I'm open to suggestions regarding venue - I don't have a co-working space to use this time around :/

**Comment by VanessaNimmo** [comment]
I've got a few ideas of who to ask - will let you know how I go!

**Comment by VanessaNimmo** [comment]
Coder Academy are happy for me to book our classroom for us to practice in - what time suits? 6-7 the Wednesday before (Jan 23rd)?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by tcn33** [comment]
@VanessaNimmo I have a room booked at CultureAmp from 1pm to 2:50pm - if you can make that, great. Otherwise let's go for maybe 5-6 at Coder Academy?

**Comment by VanessaNimmo** [comment]
Yep I can make that time. Thanks!

**Comment by tcn33** [comment]
Let's meet in the lobby at 31 Queen St at 1pm on Wednesday. Cool?

**Comment by VanessaNimmo** [comment]
Great - thanks!

**Comment by fbvilela** [comment]
https://www.youtube.com/watch?v=A6JQ9fUhtcA

@VanessaNimmo
