### ISSUE TITLE
Ruby Newbies: Knitting and TDD

### ISSUE THREAD

**Issue by colquhounking** [rails-oceania/melbourne-ruby#119]
Length: Lightning talk - 5-10 mins

Intended Audience: Beginners

Twitter Username: @ceels

Details

How knitting shows us the importance (and some of the limitations) of TDD.

**Comment by tcn33** [comment]
Hey @colquhounking! Just wanted to check if you would you like to do a rehearsal, and if so when would be good for you?

**Comment by colquhounking** [comment]
Hi @tcn33, any evening in the week leading up would work!

**Comment by tcn33** [comment]
@colquhounking are you able to make part/all of 1pm to 2:50pm on Wednesday Jan 23rd at Culture Amp for rehearsal?

**Comment by colquhounking** [comment]
I should be able to get there by 2.30, maybe a little earlier.

**Comment by tcn33** [comment]
The address is 31 Queen St - ping me when you're in the lobby :)

**Comment by tcn33** [comment]
@fbvilela how did the recordings go last month?

**Comment by fbvilela** [comment]
https://youtu.be/Xhyn9YcwM1o 👍

**Comment by fbvilela** [comment]
@quintrino

your talk is here https://www.youtube.com/watch?v=TgC6YyKiWnI&t=68s

there was no github issue to paste this on
