### ISSUE TITLE
The Rails Camp Project

### ISSUE THREAD

**Issue by saramic** [rails-oceania/melbourne-ruby#120]
retrospect on what was [#TheRailsCampProject](https://twitter.com/hashtag/TheRailsCampProject?src=hash) at [Rails Camp 24 Hobart Woodfield Nov 2018](https://railscamp24.wordpress.com/) - a review of the amazing experience of @SelenaSmall and @saramic pairing with 36 awesome Rails Campers in 56 hours. A plea for joint coding project at the next rails camp.

20 min

Perfect for end of April in preparation for the next [Rails Camp 25 Perth May 2019](https://rails.camp/#au_may_2019)

**Comment by tcn33** [comment]
Still on for April @saramic?

**Comment by saramic** [comment]
Yes @tcn33 @SelenaSmall and I are good to go for Wed 24th April!

**Comment by pat** [comment]
Hi Selena & Michael - just a quick note to let you know I'm hosting the meet tonight, as Ryan and Toby can't make it - so feel free to find me before the proceedings kick off, we can check your laptop setup.

**Comment by saramic** [comment]
@colquhounking and @VanessaNimmo I think we can close this one off as it was done April 2019 - shame there was no recording :(

**Comment by VanessaNimmo** [comment]
Good point thanks @saramic, and sorry about the recording :(
