### ISSUE TITLE
Avoiding Arrest with Rubocop

### ISSUE THREAD

**Issue by saramic** [rails-oceania/melbourne-ruby#121]
on the success of @quintrino great presentation of his 3rd favourite gem, pry, https://youtu.be/TgC6YyKiWnI I would like to see his 2nd favourite gem

**Comment by tcn33** [comment]
@quintrino Are you in for this month or is @radar trolling 😆

**Comment by fbvilela** [comment]
https://youtu.be/PkZTlvLmpvw @VanessaNimmo here we go, first video of many. they are going up

**Comment by VanessaNimmo** [comment]
Thanks @fbvilela!
