### ISSUE TITLE
Nick Wolf's all time favourite Gem

### ISSUE THREAD

**Issue by saramic** [rails-oceania/melbourne-ruby#122]
on the success of @quintrino great presentation of his 3rd favourite gem, pry, https://youtu.be/TgC6YyKiWnI I would like to see his all time favourite gem

**Comment by davich** [comment]
Let's not forget his 4th favourite! I hear it's a doozy!

**Comment by owlfox** [comment]
0th also please! 😆

**Comment by VanessaNimmo** [comment]
@quintrino, I feel like we had a conversation where we talked about this happening in August? Is that correct, and if so is that still suitable?

**Comment by quintrino** [comment]
@VanessaNimmo We did, but I'll now have to push that back.

**Comment by VanessaNimmo** [comment]
No worries, @quintrino What would be a good timeline for you?

**Comment by fbvilela** [comment]
https://www.youtube.com/watch?v=ECBfynL_BzU
