### ISSUE TITLE
Snek - developing and running a coding game for Railscamp

### ISSUE THREAD

**Issue by mtcmorris** [rails-oceania/melbourne-ruby#123]
# What

I wrote a game, [Snek](https://github.com/ferocia/snek), for people to enjoy and contribute to at Railscamp Perth.  

Can give a ~20 mins into the What, How, Why of writing this game for Railscamp, what worked well for the project and also some of the winning strategies employed by participants.

**Comment by fbvilela** [comment]
https://youtu.be/L8Ql70FOWhE
