### ISSUE TITLE
Tiny Turing Toys: Tapes, States, and Breaks

### ISSUE THREAD

**Issue by xaviershay** [rails-oceania/melbourne-ruby#125]
A talk for June perhaps? It'll be fun! I've been going deep on turing machines recently, got a ripper of a story. There'll be code, history, and zero chance of it being relevant to anyone's day job.

I see there are 20min slots, can easily fill that but will take 40min if that's an option.

**Comment by VanessaNimmo** [comment]
Would it work as two 20-minute talks with pizza in-between them? 40 minutes in one hit is a lot after a day at work but with a bit of a break we'd get to hear all the cool stuff you have to say.

**Comment by xaviershay** [comment]
yes definitely, love talks with breaks

**Comment by VanessaNimmo** [comment]
Great! Let's call it a double bill from you for the June Meetup then :)

**Comment by fbvilela** [comment]
https://youtu.be/JJ5oQ6bya-I

**Comment by xaviershay** [comment]
thank you!
