### ISSUE TITLE
Presentations Meet - 28th January 2015

### ISSUE THREAD

**Issue by pat** [rails-oceania/melbourne-ruby#13]
Confirm Speakers:

- [x] @sporto: Using Webpack with Rails
- [x] Katsuyoshi Yabe (Contacted via Meetup; awaiting reply)
- [x] Mel Sherrin: Can I start that new business? And what does your employment contract (or shareholder agreement) actually say.

Hosting: @mariovisic with @pat around for moral support

TODO:
- [x] Announce' event on Meetup
- [ ] Email rails-oceania list announcing the event
- [x] Order alcohol from Dan Murphy's
- [x] Order soft drinks
- [ ] Order food from Miss Chu

**Comment by sporto** [comment]
Hi Pat and Mario
I'm still happy to do this.

Cheers
Sebastian

**Comment by pat** [comment]
Thanks Sebastian :)

**Comment by pat** [comment]
Oh, and did you have a topic in mind?

**Comment by sporto** [comment]
Yes, I will do a talk about using Webpack with Rails

> Pat Allan <mailto:notifications@github.com>
> 22 January 2015 8:34 pm
>
> Oh, and did you have a topic in mind?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rails-oceania/melbourne-ruby/issues/13#issuecomment-70993754>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by pat** [comment]
Great, thanks :)

**Comment by kay1759** [comment]
Dear Pat an Mario, I will do my best

**Comment by pat** [comment]
Excellent, thank you :)
