### ISSUE TITLE
Talk: Introduction to Mutation Testing

### ISSUE THREAD

**Issue by tomdalling** [rails-oceania/melbourne-ruby#130]
Mutation testing is a very rigorous, but relatively unknown, approach to testing code. In this talk, I'd run everyone through:

1. What mutation testing is
1. How to do it in Ruby
1. The kinds of problems it will uncover in your code
1. When you might (or might not) want to use it

**Comment by VanessaNimmo** [comment]
Looks cool! Thanks for submitting!

How long is this talk? Is it suitable for a 20-minute presentation?
Would you like to do it at the July Meetup? It is on the 31st.

**Comment by tomdalling** [comment]
The talk isn't written yet, but I can aim for 20 mins, and I should be able to have it ready for the July Meetup. I don't think the content will be too difficult to write, because it's mostly going to be from experience, so it won't need much research.

**Comment by VanessaNimmo** [comment]
Great! Will add you to the July lineup.

**Comment by tomdalling** [comment]
Nice, see you then!

**Comment by VanessaNimmo** [comment]
Hi @tomdalling! Just a final check that you are good to go this Wednesday?

**Comment by tomdalling** [comment]
Yep, I'm good to go @VanessaNimmo. Am I pre- or post- pizza?

**Comment by VanessaNimmo** [comment]
Great! @tomdalling let's put you on first, so pre-pizza.

**Comment by VanessaNimmo** [comment]
@tomdalling Just letting you know that talks on this night weren't recorded as there was a technical issue. Usually we wait till we have a talk video to close the issue but as there won't be one I'm closing it off now. Sorry about that!
