### ISSUE TITLE
[Talk Proposal] Never Give Up: A Tale of Test Automation on Rails

### ISSUE THREAD

**Issue by clockworkpc** [rails-oceania/melbourne-ruby#131]
## Summary
A humble  software tester uses the power of Ruby on Rails to overcome insurmountable barriers to test automation.

### Speaker
Alexander Garber, Test Automation Engineer at Profectus Group.
### Length
About 20 minutes.
### Code complexity
Very simple: comprehensible to those fluent in Ruby and non-coders alike
### Key takeaways
* Ruby on Rails is excellent for prototying a concept, even in a Java/C# company.
* RSpec for unit tests, Cucumber for feature tests.
* Write just enough code to pique the interest of decision maker.
* A prototype does not need a UI, but a CLI is worthwhile.
* Work offline in transit, online at home
* Think about the code, talk about the benefits
* Hunger and pain can be your friends

**Comment by VanessaNimmo** [comment]
Looks really interesting! We have two talks for July already - how is August looking for you?

**Comment by clockworkpc** [comment]
> Looks really interesting! We have two talks for July already - how is August looking for you?

August works for me: that'll give me plenty of time to refine the talk and make sure that it keeps to a strict time limit.

**Comment by clockworkpc** [comment]
I regret to inform RORO that I cannot deliver this talk after all.  Apologies for the inconvenience.

**Comment by VanessaNimmo** [comment]
@clockworkpc I haven't heard from you if you want to deliver this at a different time or not at all. Please let me know which you would prefer.

**Comment by clockworkpc** [comment]
@VanessaNimmo, unfortunately my current role precludes me from giving this talk in the foreseeable future.  If my circumstances change I'll be very keen to put myself forward again.

**Comment by VanessaNimmo** [comment]
@clockworkpc I'll close it for now then so I don't keep trying to schedule it when I look at the repo, but feel free to re-open it in the future if you would like to present it.
