### ISSUE TITLE
[Talk proposal] MITM attacking your own site to a better UI

### ISSUE THREAD

**Issue by geelen** [rails-oceania/melbourne-ruby#132]
## Summary

There are a lot of benefits to a fully separated frontend and an API-only backend in Rails: you can iterate faster, use fancy new hosting platforms like Netlify, and allow each of your developers to focus either on backend (business logic) or frontend (customer-facing features). But what if you're not there yet?

While building a product in this space, I came across a use-case that I think will be really interesting to anyone who's still shipping a _mostly_ monolithic Rails app, but coding most of the complex UI in JS using Webpack. It uses a new open-source frontend bundle format called FABs (for Frontend Application Bundle, more info at https://fab.dev) that I've been developing, proxies your existing staging app and makes it _feel_ like you're deploying a new version of your app with every commit!

I'd love to give this technique a bit of an audience to see whether it's worth pursuing and releasing as its own open-source tool.

### Speaker

Glen Maddern, once a Rails engineer, now does JS. At least 5+ years since my last Roro talk.

### Length

Probably < 10 minutes, mainly introducing some concepts then going through the major parts of a ~200 line MITM server. If there's more time I'm happy to lay more groundwork and talk a bit more about the potential, but happy to fit into a lightning talk slot.

### Code complexity

Simple but very non-Rails-y. Uses basic HTTP concepts but because it's actually JS I'll go through it a bit slower.

### Key takeaways

You don't have to completely rebuild your app to upgrade your UI iteration speed. You just need to hack your own site a little.

---

I'm not going to be in Melbourne that much longer, and I already have a clash for August 28 (I could move it if that's the only time possible). Ideally I'd love to do this as a lightning talk this month if there's room, or a "proper" talk in September?

**Comment by VanessaNimmo** [comment]
Hi Glen! Apologies for not seeing this earlier. It feels like something I'd really like to see a full 20 minutes on in September. Is that ok with you @geelen?

**Comment by geelen** [comment]
Sounds good! That'll be the 25th of Sept, yeah?

**Comment by VanessaNimmo** [comment]
Yep Sept 25th! Looking forward to hearing your talk!

**Comment by VanessaNimmo** [comment]
Unfortunately no video was recorded for this meetup - apologies!
