### ISSUE TITLE
A quick look at some of the improvements and new features in Ruby 2.7

### ISSUE THREAD

**Issue by tristanpenman** [rails-oceania/melbourne-ruby#133]
This is a talk idea that I've been playing around with for a while:

I think all Ruby developers, beginners and experts alike, will have found themselves tripped up by the quirks of the language and standard library at various points in time. Little things, like 0 being truthy, can be very surprising for people coming from other languages. And the features that lead to this, such as everything being an object, while powerful, can lead to confusion.

I like to think of these quirks as Ruby's Rough Edges.

In this talk, I will go through some common (and not-so-common) examples of these Rough Edges, and show how the Ruby community has worked around them, or even taken advantage of them in creative ways, leading to the more polished Ruby experience we have today.

--

This topic is probably well suited to around 20 minutes.

**Comment by VanessaNimmo** [comment]
Hi @tristanpenman. Sounds interesting! We currently have space for a 20 minute talk in August or September - do either of them suit?

**Comment by tristanpenman** [comment]
Great! I could do September.

**Comment by VanessaNimmo** [comment]
Great @tristanpenman let's lock it in!

**Comment by tristanpenman** [comment]
@VanessaNimmo, it looks like I won't actually be able to make it to the meetup this month due to a conflicting work commitment. Can we push the talk back to the October meetup?

**Comment by tristanpenman** [comment]
Just wanted to follow up on this to make sure that someone from the organiser team has seen my previous message.

**Comment by VanessaNimmo** [comment]
Hi @tristanpenman yep got your message, just only reply to RORO messages a couple of times a week rather than every day :)

Thanks for letting us know you can't speak this month. October is already too full for another 20-minute talk. We'll chat about what talks are coming up and get back to you soon.

**Comment by tristanpenman** [comment]
Sounds good.

**Comment by VanessaNimmo** [comment]
Hey @tristanpenman - how about November for this talk?

**Comment by tristanpenman** [comment]
That works for me 👍

**Comment by VanessaNimmo** [comment]
Hi @tristanpenman! New features also sounds like a great talk - do you want to change the title of this issue to reflect that? We're happy for a new features talk to happen in November.

**Comment by tristanpenman** [comment]
Will do

**Comment by VanessaNimmo** [comment]
Unfortunately the video recording did not work on the evening this talk was presented, so no video is available.
