### ISSUE TITLE
is my rails good enough to go to RailsCamp?

### ISSUE THREAD

**Issue by squiggla** [rails-oceania/melbourne-ruby#134]
I am challenging my sister @tamadillo for a ticket to go to RailsCamp Melbourne Nov 2019 by seeing if I have learned enough rails by the October meetup. A quick journey of what I have learnt over 3 months programming and some live code (I hope). Let the audience decide who is more deserving of the 1 ticket that my father @saramic has bought for us.

10-minute presentation, some live coding, October 2019 meetup

**Comment by VanessaNimmo** [comment]
High stakes @squiggla! Have added you to the October milestone and looking forward to hearing your talk.

**Comment by xaviershay** [comment]
@saramic thunderdome with your kids, brutal 🤘

**Comment by VanessaNimmo** [comment]
https://www.youtube.com/watch?v=uIj-ipbPI3A
