### ISSUE TITLE
Lightning talk: Rails as a static site generator

### ISSUE THREAD

**Issue by antulik** [rails-oceania/melbourne-ruby#135]
The goal is to keep the talk under 5 min

**Comment by VanessaNimmo** [comment]
Sounds interesting! When suits you to do this talk? We don't have a specific night scheduled for lightning talks as yet, but if its under 5 minutes we could probably fit it in any month that suits you.

**Comment by colquhounking** [comment]
October might be good? squiggla and tamadillo will either be doing a joint talk or two short talks. What do you think @antulik?

**Comment by antulik** [comment]
I can do August, and will submit another proposal for October.

I'd like to popularise such format and encourage other people to start presenting lighting talks. So will throw a twist, if people want me to give a lighting talk in October, they should also give a lighting talk as well. Give one, get one free deal :) So potentially there will be two lighting talks in october if everything goes well :)

**Comment by colquhounking** [comment]
Hey Anton! It would be great if you could do August! (This Wednesday!)

**Comment by fbvilela** [comment]
https://youtu.be/wgz2-zpyLvM
