### ISSUE TITLE
My testing experience with TCR

### ISSUE THREAD

**Issue by saramic** [rails-oceania/melbourne-ruby#136]
well I have none, but now that I have a public issue open I am sure I will find time to prepare a short (_~20min_) presentation to show what it is `test && commit || revert` TCR way of writing test driven code. I am good to go for **Augutst 2019**

I will try to keep this issue somewhat updated in case this grows into a longer presentation :p

**Comment by VanessaNimmo** [comment]
Great! Have added you to the August milestone. Looking forward to it!

**Comment by fbvilela** [comment]
https://youtu.be/OvtkD4O2dcE
