### ISSUE TITLE
How we use Rails to extract and democratise Business Intelligence from data at Up

### ISSUE THREAD

**Issue by cmaitchison** [rails-oceania/melbourne-ruby#137]
A deep dive into how the [Up](https://www.up.com.au) Rails monolith asynchronously transforms data structured by the operational DB schema into data structured in an analytical schema, in order to power business intelligence queries - all within the monolith.

We use [Multiverse](https://github.com/ankane/multiverse) to connect certain ActiveRecord objects to another Postgresql database. We then use background jobs to continually poll the operational tables in order to extract the data, strip it of Personally Identifiable Information (PII) and then load it into an analytics database, with different accessibility characteristics to the operational database.  We then point the open source BI tool, [Metabase](https://metabase.com), at our analytics database and democratise the access to business intelligence around our organisation without any detriment to the privacy of our customers.

In this talk I will discuss:
  - The details of how to connect your ActiveRecord objects to multiple databases, and why you would do that.
  - The differences in a transactional schema and an analytics schema (OLTP vs OLAP), aka Data Warehousing or Star Schema
  - How to transform data between the two structures
  - The privacy concerns around performing business intelligence on operational data
  - The benefits of the democratisation of access to business intelligence
  - Why we chose Metabase as our window into our analytics database

**Comment by VanessaNimmo** [comment]
Sounds fantastic @cmaitchison! How long is this talk, and how soon would you like to do it?

**Comment by cmaitchison** [comment]
Hi @VanessaNimmo. I was thinking it could be a 30-40 minute talk that I could give next month.

**Comment by colquhounking** [comment]
@cmaitchison Would October work for you?

**Comment by cmaitchison** [comment]
It certainly would 👍

**Comment by cmaitchison** [comment]
I’ve got this down to about 20 minutes to fit better with the standard format 👍

**Comment by colquhounking** [comment]
Woo! Thank you! Looking forward to it :)

**Comment by ZimbiX** [comment]
Great talk, @cmaitchison! Cheers

What was your referral link again? =P

**Comment by VanessaNimmo** [comment]
https://www.youtube.com/watch?v=Rk31iOgJhJM
