### ISSUE TITLE
[Lightning Talk] 10 non-code tips that could help you be a better team member

### ISSUE THREAD

**Issue by cmaitchison** [rails-oceania/melbourne-ruby#138]
A quick overview of some of the lessons I've picked up from managing the high-performing engineering team at [Up](https://www.up.com.au).

**Comment by cmaitchison** [comment]
@VanessaNimmo Hi Vanessa. Happy to give this at RORO tomorrow if there is still an open spot.

**Comment by VanessaNimmo** [comment]
That would be fantastic! Thanks @cmaitchison!

**Comment by fbvilela** [comment]
https://youtu.be/kdJzevi0aMQ
