### ISSUE TITLE
I am going to rails camp, again!

### ISSUE THREAD

**Issue by tamadillo** [rails-oceania/melbourne-ruby#139]
so big brother @squiggla want's to go to rails camp on the 1 ticket my dad @saramic has funded for "us". Well I don't think so. Let the audience decide, some of my learnings in coding and maybe even some live coding? look i even have a [water cycle](https://water-cycle.herokuapp.com/) [github](https://github.com/tamadillo/water-cycle) thing I did in react for a year 7 project in science! 10 min lightning talk October 2019 meetup

looking forward to destroying you little @squiggla

**Comment by VanessaNimmo** [comment]
Looking forward to hearing it @tamadillo!

**Comment by VanessaNimmo** [comment]
https://www.youtube.com/watch?v=uIj-ipbPI3A
