### ISSUE TITLE
Presentations Meet - 25th February 2015

### ISSUE THREAD

**Issue by pat** [rails-oceania/melbourne-ruby#14]
Confirm Speakers:

- [x] @vonconrad - Reporting and the First Law of Holes
- [x] @gabrielrotbart - Testing Microservices
- [x] @akampjes - Rails security TL;DR

Hosting: @mariovisic with @pat around for moral support, and introducing @quamen as one of the new hosts.

TODO:
- [x] Announce event on Meetup
- [x] Email rails-oceania list announcing the event
- [x] Order alcohol from Dan Murphy's
- [x] Order soft drinks
- [x] Order food from Miss Chu

**Comment by pat** [comment]
Hi all - sorry for the late notice about this event. If anyone can no longer present, do let us know!

**Comment by akampjes** [comment]
@pat  Could you rename my talk to, "Rails security TL;DR"
How long are are the talks?

**Comment by pat** [comment]
I'd be wary of going longer than 20 minutes, as that's about the point most people's brains shut off (especially if food has arrived). Shorter is fine too - there are no rules around this :)

**Comment by vonconrad** [comment]
Very much looking forward to @akampjes' talk!

I don't have a good title for mine. I've been tossing up two talks--one about security/data protection, another about not to digging oneself into a hole when it comes to reporting. Seeing how Andrew is already talking about security, I'll probably go with the latter.

**Comment by akampjes** [comment]
Sweet, 20minutes is perfect.

@vonconrad rad, you're into security too! We'll have to get a beer after or something.

**Comment by vonconrad** [comment]
@pat Ideal aspect ratio for slides? Standard (4:3) or widescreen (16:9)?

@akampjes Sounds good! :smile:

**Comment by akampjes** [comment]
@vonconrad try 16:9, whatever is at the bottom of your slides, no-one will be able to see because the person in front of them's head is in the way (in this venue).
If it's 4:3 and you make 16:9 slides you can just have black bars where no-one can see anyway.

**Comment by pat** [comment]
4:3 will definitely be fine (it's what our sponsor deck uses)... not sure about 16:9, I should check.

**Comment by pat** [comment]
But @akampjes's point about bottom and top of the slides are harder to see are worth keeping in mind :)

**Comment by pat** [comment]
@vonconrad: sounds like you've chosen a topic, going by your tweets about slides? :) Care to let me know what to call your talk, so I can announce it to the list & meetup?

**Comment by vonconrad** [comment]
@pat It's called "Reporting and the First Law of Holes."

**Comment by vonconrad** [comment]
I'm at 102 slides now. :grin:

**Comment by pat** [comment]
Crazy ;)

**Comment by quamen** [comment]
This totally happened :+1:

**Comment by mariovisic** [comment]
Can confirm, did happen!

**Comment by quamen** [comment]
@mariovisic I was unable to close this issue, is there some bits you can flip in github to give myself and @mattallen higher privileges?

**Comment by mariovisic** [comment]
@quamen you'll have to get added to this github team: https://github.com/orgs/rails-oceania/teams/melbourne-ruby

Ping anyone who is listed as an 'owner' on this page: https://github.com/orgs/rails-oceania/people

**Comment by quamen** [comment]
@pat could you add me to the melbourne-ruby team?

**Comment by pat** [comment]
Done.
