### ISSUE TITLE
how I created an interactive slide show

### ISSUE THREAD

**Issue by saramic** [rails-oceania/melbourne-ruby#140]
How I built an interactive slide show for live audience participation using Rails and GraphQL and React - it will be awesome

5min lightning talk - maybe October?

**Comment by VanessaNimmo** [comment]
Hey @saramic! Is this a talk you actually want to give? If not we can close the issue :)

**Comment by saramic** [comment]
@VanessaNimmo absolutely! this will be international standard 5min lightning talk having the users actively interact with my slides getting me to tell them how I built the interactive slides! it will be amazing - the users can "choose their own adventure" as to how long I stay on a slide and what slide I go to next

**Comment by VanessaNimmo** [comment]
@saramic Great! How soon would you like to deliver it?

**Comment by VanessaNimmo** [comment]
https://www.youtube.com/watch?v=uIj-ipbPI3A
