### ISSUE TITLE
Work-life balance - what it is and how to get it

### ISSUE THREAD

**Issue by tcn33** [rails-oceania/melbourne-ruby#141]
Lots of people (me included) have trouble with establishing boundaries between their work and home lives. I’d like to see a talk on how you navigated this and some tips on establishing a healthy balance.

**Comment by dnch** [comment]
Ooooh, I love fairy-tales! :D

**Comment by elle** [comment]
Also can do a talk about this topic

**Comment by VanessaNimmo** [comment]
https://youtu.be/l5o9gq50ZcE 🌴
