### ISSUE TITLE
[Lightning talk] (comedy) HOWTO: Become a 10x rockstar developer

### ISSUE THREAD

**Issue by biancaG** [rails-oceania/melbourne-ruby#142]
The story of how I became a 10x rockstar developer using the rockstar programming language.

**Comment by VanessaNimmo** [comment]
Hi @biancaG - is this a 5-minute lightning talk? And when would you like to present it?

**Comment by biancaG** [comment]
Yes, and the next meeting if there's a spot available.

**Comment by biancaG** [comment]
Also, this *must* be clearly described as a comedy, I don't want something published that makes it sound like I actually think I'm a 10x rockstar in the common meaning.

**Comment by VanessaNimmo** [comment]
Yep next meeting is possible @biancaG. Can promise to describe as comedy :)

**Comment by VanessaNimmo** [comment]
Unfortunately no video was recorded for this meetup - apologies!
