### ISSUE TITLE
Proposed Talk: A Request for Comments

### ISSUE THREAD

**Issue by dnch** [rails-oceania/melbourne-ruby#144]
When did comments become a bad thing? A short exploration of why the tide of public opinion has turned against comments, why I believe it's unhelpful and a light smattering of opinion about how to leverage them to help you and your team succeed.

**Comment by VanessaNimmo** [comment]
Hi @dnch! Are you thinking 20 minutes for this or shorter? And how far away are you thinking for presenting?

**Comment by VanessaNimmo** [comment]
Hey @dnch! Have added this to Jan as per our chat on Wednesday, but can be moved to whenever suits. Just let me know :)

**Comment by VanessaNimmo** [comment]
Hello! Happy New Year! How are you feeling about doing this talk at the January meetup now that it is January?

**Comment by VanessaNimmo** [comment]
@dnch thoughts on the above please?

**Comment by VanessaNimmo** [comment]
@dnch having not heard from you at all to confirm I'm going to take this off the January Meetup. Looking forward to hearing it when the timing is better.

**Comment by VanessaNimmo** [comment]
Talk video: https://youtu.be/OEQkgZfMoZw
