### ISSUE TITLE
API request idempotency

### ISSUE THREAD

**Issue by ZimbiX** [rails-oceania/melbourne-ruby#146]
In the tech book club at GreenSync, we've been reading [Designing Data-Intensive Applications by Martin Kleppmann](https://dataintensive.net/) - an absolutely amazing book! It's brought to our attention the difficulty of cleanly dealing with the situation where an update request from an app to our central service, [deX](https://dex.energy), gets lost somewhere along the way. This could be before or after deX processes the request, but the app never receives a response. Is it safe for the app to perform it again? Or will the data be stored twice?! Who knows!

This talk will cover this problem and its solution: What idempotency is, when you should have it in your API, and how we (will have =P) added it to deX.

**Comment by VanessaNimmo** [comment]
Hi @ZimbiX! Is this a 20-minute talk or something shorter? And what sort of timeframe are you looking at for presenting it?

**Comment by ZimbiX** [comment]
20-30 minutes I reckon. In a couple of months

**Comment by ZimbiX** [comment]
I don't think we're going to get to this for a while, so I think I'll close this issue and re-open when/if we do
