### ISSUE TITLE
Sorbet: first impressions

### ISSUE THREAD

**Issue by HashNotAdam** [rails-oceania/melbourne-ruby#147]
Sorbet, a type checker for Ruby, created a lot of buzz when it was announced. Inevitably, with a language that prides itself on expressiveness, simplicity, and flexibility, the introduction of something which brings us closer to Java was going to create loud, polarising opinions.

Now that it is in the wild, it seems like a good time to have a discussion that spans experience levels including:

- what even is a type?
- what is style checking?
- why should I care?
- what are the pros and cons of strict types?
- how does Sorbet tackle the concept?
- what does it look like in action?
- what is the real-world experience like?
- what are Sorbet's strengths and weaknesses?
- should I use it?

While this is an interesting topic, it can get a little dry so I think it'll need to be kept strictly inside the 20-minute slot.

I would expect to start drafting the talk soon while the first impressions are still fresh so can be flexible about when to give it.

**Comment by HashNotAdam** [comment]
Sounds great, @colquhounking

**Comment by colquhounking** [comment]
Woo!

**Comment by ZimbiX** [comment]
I'm disappointed to have missed last month - very keen to see the recording of this!

**Comment by HashNotAdam** [comment]
@ZimbiX TBH, it was only worth watching for the free icecream ;)

**Comment by VanessaNimmo** [comment]
Unfortunately the video recording did not work on the evening this talk was presented, so no video is available. Sorry @ZimbiX!
