### ISSUE TITLE
Talk proposal: Enter the Matrix

### ISSUE THREAD

**Issue by StaphSynth** [rails-oceania/melbourne-ruby#148]
A talk about setting up test matrices to test your code against multiple versions of its dependencies and multiple versions of Ruby.

**Comment by VanessaNimmo** [comment]
Cool! Is this a 20 minute talk? And how soon are you thinking for presenting it?

**Comment by StaphSynth** [comment]
Yeah I was thinking of somewhere around 20 min. Might be a bit shorter (I'll try not to overload people with technical stuff). I can do whenever you have space.

**Comment by VanessaNimmo** [comment]
Have added to Jan as per the chat on Wednesday. Hope that's cool!

**Comment by VanessaNimmo** [comment]
Hello! Happy New Year! How is the January meetup feeling for this talk now that it's January?

**Comment by VanessaNimmo** [comment]
@StaphSynth thoughts on the above please?

**Comment by StaphSynth** [comment]
@VanessaNimmo sorry about the delay. Yep, all go for January!

**Comment by VanessaNimmo** [comment]
Sweet! See you then!
