### ISSUE TITLE
Talk Proposal: Writing Ruby Gems

### ISSUE THREAD

**Issue by pat** [rails-oceania/melbourne-ruby#149]
Essentially, polishing up the talk I just gave at Rails Camp with some better slides and an actual rehearsal or two, covering the following:

* What are gems?
* Why would you write gems?
* File structures and naming
* Adding executables
* Building and publishing
* Licenses, Versions and READMEs
* Testing
* Integrating with Rails

Happy to present this sometime early in the new year. Might need 30 minutes for it (I feel like it took that long, possibly a touch longer, at Rails Camp?)

**Comment by VanessaNimmo** [comment]
Hi @pat! Given our chat re the camp length of this talk, do you want to schedule 30 minutes for this one or make it a 40 or 45 minutes slot?

**Comment by pat** [comment]
I feel like 40-45 is maybe the better target, given people will likely have questions as well, and it means I can keep the Rails-specific stuff in which may be more interesting to those with a bit more experience.

Do you have some idea of which month you'd like this scheduled in for? (i.e. do I need to have it ready for a fortnight's time? 😅)

**Comment by VanessaNimmo** [comment]
Let's put aside a longer time for this talk, which means earliest available is March. Does that work for you?

**Comment by pat** [comment]
March works 👍

**Comment by VanessaNimmo** [comment]
https://www.youtube.com/watch?v=jGQTP3gqQ1U
