### ISSUE TITLE
Presentation Meet - 25th March 2015

### ISSUE THREAD

**Issue by quamen** [rails-oceania/melbourne-ruby#15]
Confirm Speakers:

March Talks:
  - [x]  ~~@joneslee85 - Lotus for Web APIs~~
  - [x]  @dreJ2k - Bike Trip Planner - Web App
  - [x]  @quamen - Black Box Testing

Hosting: @mattallen with @quamen around for moral support.

TODO:

- [x] Announce event on Meetup
- [x]  Email rails-oceania list announcing the event
- [x]  Order alcohol from Dan Murphy's
- [x]  Order soft drinks
- [x]  Order food from Miss Chu

**Comment by pat** [comment]
@joneslee85, @dreJ2K: just mentioning you in case you missed the original notification (not sure you get alerts when edits add your username in) :)

**Comment by drej2k** [comment]
Hi Pat,

Thanks for the add in! 

The guys(@vasilly and @mike1372) and myself are currently drafting our talk. Will get back to you with the title shortly

**Comment by quamen** [comment]
@drej2k cool. If you could let me know soon what the title is, then I'll be able to update the meetup page and send out the announcement email.

**Comment by quamen** [comment]
@joneslee85 can't make this month, I've contacted one of the speakers lined up for next month to see if they want to speak this month. Will update the list above if they get back to me.

**Comment by drej2k** [comment]
@quamen I did post the title information on wednesday night and was suprised not to see it here this morning. Here it is again:
Title: Bike Trip Planner - Web App 
Background: A simple single page web app utilising Ruby, Rails, Postgresql, canvas and javascript

**Comment by drej2k** [comment]
@quamen, @pat 
I am wondering if there will be a wireless presentation clicker that we could use on Wednesday night?

**Comment by quamen** [comment]
@drej2k I do not own one and I don't think inspire 9 does either.

**Comment by pat** [comment]
Yeah, I'm afraid we don't have a spare one floating around at Inspire9, sorry.

**Comment by mattallen** [comment]
I have one.


-- 
Matt Allen
0413 777 771

On 23 March 2015 at 9:20:02 am, Pat Allan (notifications@github.com) wrote:

Yeah, I'm afraid we don't have a spare one floating around at Inspire9, sorry.

**Comment by drej2k** [comment]
@mattallen 
Fantastic Matt, could please bring it on the night?

**Comment by drej2k** [comment]
@quamen 
On meetup.com/Ruby-on-Rails-Oceania-Melbourne/
Would it be possible to update the speakers list to:
Michael Kempster, Vasko Traikovski and Andre Vidic - Bike Trip Planner 
?
Thanks

**Comment by quamen** [comment]
@drej2k done. Sorry about the original not including everyone.

**Comment by mattallen** [comment]
Indeed :)


-- 
Matt Allen
0413 777 771

On 23 March 2015 at 10:35:16 pm, Andre (notifications@github.com) wrote:

@mattallen
Fantastic Matt, could please bring it on the night?
