### ISSUE TITLE
My learning journey through different careers

### ISSUE THREAD

**Issue by nhunghoang1** [rails-oceania/melbourne-ruby#150]
My name is Emily Hoang. I'm a graduate software developer at ThoughtWorks - a global IT consultancy. I'd like to share with you all 'My learning journey through different careers'. Some parts of my presentation will be written in Ruby with some real simple classes. It's very easy to understand, especially for junior developers. The presentation is in Pecha Kucha style (20 slides, 20 seconds per slide).
Please give me some feedback afterwards so I can improve my presentation skills as this will be my second time presenting in public!

**Comment by VanessaNimmo** [comment]
Hi Emily! Looking forward to hearing your talk. Have you been to RORO before? Do you know what time it all happens and so on?

**Comment by nhunghoang1** [comment]
Hi Vanessa,
I've been to the meetup 2,3 times. I believe that from 6 - 6:30,
everyone will just hang around and network. Then at 6:30, the talk will
start. I told Ryan that my presentation will be the first one. Hopefully,
it will be ok.
It would be great if you could confirm the agenda just in case I got it all
wrong.
Cheers,
Emily Hoang

**Comment by VanessaNimmo** [comment]
Great that you are familiar with the format. Because your talk is short, going first is fine. At 6.30 we'll get everyone seated and announce things - first talk usually starts some time between 6.30 and 6.45, depending on how fast people get settled and how many announcements there are. See you tomorrow!

**Comment by nhunghoang1** [comment]
Perfect, see you there.

**Comment by VanessaNimmo** [comment]
Unfortunately the video recording did not work on the evening this talk was presented, so no video is available.
