### ISSUE TITLE
Talk Proposal: This Talk Has Been Disabled (a talk on accessibility)

### ISSUE THREAD

**Issue by lisushka** [rails-oceania/melbourne-ruby#151]
This Talk Has Been Disabled is a talk on accessibility, with primary focus on how web developers can avoid and fix the most common/impactful barriers to access.

The talk is 45-50 minutes long, and can probably be cut to 40 if necessary.  I've given it multiple times before, and so I can present whenever is convenient.  I can also provide a synopsis and the slide deck from the last time I gave this talk on request.

**Comment by VanessaNimmo** [comment]
Thanks @lisushka! We would be delighted to have you either February 26th or March 25th - take your pick :) 45 minutes is ok by us, we would aim to have you start around 7.30 after refreshments. Does that work?

**Comment by lisushka** [comment]
Start time is agreeable.  February would be better for me, so let's do that.

**Comment by VanessaNimmo** [comment]
Great! Let's lock in February :)

**Comment by fbvilela** [comment]
https://www.youtube.com/watch?v=vNj8ItVcwsE

**Comment by VanessaNimmo** [comment]
With CC: https://www.youtube.com/watch?v=wPlDNZtQ6QM&t=25s
