### ISSUE TITLE
How to apply engineering principles to getting approvals

### ISSUE THREAD

**Issue by wakeless** [rails-oceania/melbourne-ruby#152]
Title is a WIP

This talk takes a few principles that we as rubyists hold near and dear and applies them to the task of getting your project green-lighted. This applies to any project in your team, or larger.

**Comment by wakeless** [comment]
Weirdly, don't seem to be able to add labels, but it is 40 minutes.

**Comment by VanessaNimmo** [comment]
Thanks! That was going to be my first question :) Approximately when do you think it will be ready to present?

**Comment by wakeless** [comment]
@VanessaNimmo I could present it at the next RORO. It's basically ready to go

**Comment by colquhounking** [comment]
Hi there! would you consider presenting this as an online talk? It doesn't look like we'll be back in person for a while

**Comment by VanessaNimmo** [comment]
Thank you for presenting this excellent talk and apologies for not recording it.
