### ISSUE TITLE
Online Talk Proposal: Working with Tailwind and SVG

### ISSUE THREAD

**Issue by joshprice** [rails-oceania/melbourne-ruby#154]
I'm really loving Tailwind CSS for working server side without writing *any* CSS at all.

Inline SVGs are a real game changer for icons and vector drawings.

I've been doing this with Elixir and Phoenix but it applies just the same in a Rails app (or any other server side rendered web framework for that matter).

**Comment by colquhounking** [comment]
Hey Josh, would this be ready for April's online RORO?

**Comment by VanessaNimmo** [comment]
Hi Josh! May is also going to be online - would you like to present then?

Also, how long is this talk?

**Comment by ZimbiX** [comment]
Thanks for the talk, @joshprice! Very keen to share the video :grin:

**Comment by VanessaNimmo** [comment]
here is the video, with the caveat that there is a moment or two missing around the 2:45 mark due to technical difficulties: https://youtu.be/o9Y_uL18wZ4
