### ISSUE TITLE
Online presentation: The Curious Incident of the Shadow in the Run-Time

### ISSUE THREAD

**Issue by paulfioravanti** [rails-oceania/melbourne-ruby#155]
This talk is all about the perils of shadowing in Ruby, starting with variable shadowing, and exploring a lesser-known but worth-knowing form of shadowing that you should try and avoid in your codebase.

Intended audience - Probably intermediate upwards, but I've tried to be as beginner-friendly as possible.

Twitter username is `@paulfioravanti`.

I've previously [given this talk at ROROSyd](https://github.com/rails-oceania/roro/issues/235), so I'm happy to have this talk slotted in at whatever meetup is appropriate.

**Comment by VanessaNimmo** [comment]
Thanks, Paul! How long is this talk?

**Comment by paulfioravanti** [comment]
Last time I did it, I recall it being 15-20 minutes.

**Comment by VanessaNimmo** [comment]
hi @paulfioravanti! would you be happy to present this at our May meetup on the Wednesday the 27th?

**Comment by paulfioravanti** [comment]
Sure thing! Lock me in!

**Comment by VanessaNimmo** [comment]
Wonderful! The meeting will be open from 6pm, with announcements and presentations starting at 6:30pm. I think we also have a lightning talk for the May meetup, so will probably do that one first, then your longer talk so that we can spend time on questions afterwards. See you (online) then!

**Comment by paulfioravanti** [comment]
Thanks for having me on this evening! Slides can be viewed here: https://speakerdeck.com/paulfioravanti/the-curious-incident-of-the-shadow-in-the-run-time
