### ISSUE TITLE
Talk Proposal: Minimalism in your Home(directory)

### ISSUE THREAD

**Issue by quintrino** [rails-oceania/melbourne-ruby#157]
A short talk (5 - 10 minutes) about reducing the number of hidden files in your home directory.

**Comment by VanessaNimmo** [comment]
Hey @quintrino! Confirming you were keen to do this at the May online meetup?

**Comment by VanessaNimmo** [comment]
Talk video (apologies for the delay!): https://youtu.be/NzvbcBaPhXc
