### ISSUE TITLE
View Components 101

### ISSUE THREAD

**Issue by pinzonjulian** [rails-oceania/melbourne-ruby#158]
Do you wish you could write React/Vue-like components without a single line of JS?  

Introducing the [View Component](https://github.com/github/view_component) gem by the team at Github!

In this 10-15 minute talk I’ll do a quick intro to what view component is and how you can use it to clean up, preview and test components using plain, old and boring Ruby on Rails.

**Comment by VanessaNimmo** [comment]
https://youtu.be/Lzsb-Q5Lm9g
