### ISSUE TITLE
Debugging Diversity in the Tech Industry

### ISSUE THREAD

**Issue by coderdan** [rails-oceania/melbourne-ruby#161]
I've spoken a few times on the topic of fostering diversity in technology but delivered a revised version to a team at MYOB recently and it was suggested that I present at RoRO.

The talk covers:
* Defining the problem of diversity in tech
* Defining what we mean by diversity
* What folks can do to help improve diversity and inclusion (belonging even!) in tech

Its targetted more towards men as a sort of practical guide.

**Comment by VanessaNimmo** [comment]
Thanks @coderdan! I remember it being a longer talk - was it 40 minutes and then we chatted for a bit, or was it an hour? Either way does August 26th work?

**Comment by coderdan** [comment]
Its closer to an hour but I can make it a bit shorter if you need!

**Comment by coderdan** [comment]
And yep, the 26th works!

**Comment by VanessaNimmo** [comment]
No need to make it shorter, an hour works great! See you (online) on the 26th!

On 15 Aug 2020, at 22:15, Dan Draper <notifications@github.com> wrote:

﻿

Its closer to an hour but I can make it a bit shorter if you need!

**Comment by VanessaNimmo** [comment]
Just letting you know @coderdan that we didn't end up with a lightning talk tonight, so its just you, which means you can luxuriate in an hour-long talk :) Looking forward to hearing it again!

**Comment by coderdan** [comment]
Here are my slides in case you want to share them: https://docs.google.com/presentation/d/1U5yHHaoDrSzv57waPgNMGG1Gsxcvzn7IlCmgN2b4XZw/edit?usp=sharing

**Comment by colquhounking** [comment]
Thanks, Dan!

**Comment by davich** [comment]
Hi @coderdan , Thanks for your talk. I found it super interesting. You mentioned a study where 2 mixed gender groups performed differently depending on whether they'd been told gender would influence results or not. Do you have a link to this study? I'd love to read more about it. Thanks

**Comment by VanessaNimmo** [comment]
Talk link: https://youtu.be/n9nZmNmEutk
