### ISSUE TITLE
Reflective testing

### ISSUE THREAD

**Issue by maedi** [rails-oceania/melbourne-ruby#163]
Introduce the concept of reflective testing and demo Reflekt, a new gem which makes it possible:
https://github.com/refIekt/reflekt

**Comment by colquhounking** [comment]
Hiya Maedi! Thanks for submitting a talk! What length talk are you planning? we have time for a shorter/lightning talk in September, or a longer one in November.

**Comment by maedi** [comment]
The shorter one is fine, thank you

**Comment by colquhounking** [comment]
Excellent, would you like to speak at the September meetup? Wednesday 30th?

**Comment by maedi** [comment]
OK 30th September sounds good

**Comment by VanessaNimmo** [comment]
Thanks for the talk! Vid here: https://youtu.be/yO_0JdcOND8

**Comment by maedi** [comment]
Thanks, I kept working on the tool and it's at a much better stage now than in that screencast!
