### ISSUE TITLE
Arduino on Rails

### ISSUE THREAD

**Issue by saramic** [rails-oceania/melbourne-ruby#165]
So what has **Arduino**, an open-source electronics hardware platform that reads and sets things using electrical voltages, got to do with **Rails*, a web-application framework that includes everything for database-baked web apps, got to do with each other?

well nothing, but I will present some of my experiments bringing them together.

* 15-25 min presentation
* ready for October 2020

**Comment by VanessaNimmo** [comment]
Thanks @saramic! Yes please for October 😃

**Comment by VanessaNimmo** [comment]
Thanks for the rad talk! Vid here: https://youtu.be/ASWD4EZqylU
