### ISSUE TITLE
Exercism preso - TBA

### ISSUE THREAD

**Issue by bencefulop** [rails-oceania/melbourne-ruby#166]
Name of talk: Exercism presentation (Will select problem this week)
Brief summary of the talk content: TBA
Which month's meetup you would like to present at: 25th November

**Comment by bencefulop** [comment]
I was thinking to solve the ISBN Verifier challenge: `exercism download --exercise=isbn-verifier --track=ruby`
Would that work for you?

**Comment by colquhounking** [comment]
Sounds good

**Comment by VanessaNimmo** [comment]
https://youtu.be/OFym5QlfalU 🥳
