### ISSUE TITLE
Ruby on Rails & Service Workers (PWA)

### ISSUE THREAD

**Issue by MikeRogers0** [rails-oceania/melbourne-ruby#169]
I've been messing about a little recently with Service Workers & Rails, the end result is you can have your app enter a "read-only" mode when the user goes offline (e.g. they lose network coverage). The cool thing, is it'll work without requiring converting to an SPA, so you can do when you're setup using Server Side Rendering (e.g. turbolinks + ERB templates).

The main gist of the talk will be use [webpacker-pwa](https://github.com/coorasse/webpacker-pwa) & [Workbox](https://developers.google.com/web/tools/workbox), or if you're using sprokets [serviceworker-rails](https://github.com/rossta/serviceworker-rails). 

I'd love to do a talk on it if anyone is intrested 👍 

I am in the UK right now though, so it would need to be done online :)

**Comment by colquhounking** [comment]
Hey Mike! We'd still be online for the January meet, would that suit you? We've been finding that 20-30 minute talks or 5min lightning talks have been working well with the online format. Do you have a sense of how long the talk would be?

**Comment by MikeRogers0** [comment]
@colquhounking January would be awesome!

Right now my talk is ~10 minutes I think. I'll get working on my slides over this month & get a better estimate for you 👍

**Comment by ceels** [comment]
Hi @MikeRogers0 , looking forward to this talk in January!

**Comment by MikeRogers0** [comment]
@ceels I'm excited to give it! 

I'm working on my slides this weekend, I ended up writing a blog posts ( https://mikerogers.io/2020/12/14/how-to-make-rails-work-offline-via-service-workers ) & done a quick YouTube tutorial on it also, so I'm feeling great about it :D

**Comment by MikeRogers0** [comment]
https://talks.mikerogers.io/taking-rails-offline/?view=presenter - I'm feeling pretty awesome about the talk now @ceels :) I think it'll be about 15-20 minutes or so (Depending on if we have questions & if anyone wants to see my demo apps) :D

**Comment by ceels** [comment]
Looking forward to it!

**Comment by VanessaNimmo** [comment]
https://youtu.be/FjNDrPDjm4o ❄️

**Comment by MikeRogers0** [comment]
Woo awesome, thank you!
