### ISSUE TITLE
Debugging & optimising Ruby performance

### ISSUE THREAD

**Issue by jkotchoff** [rails-oceania/melbourne-ruby#170]
Demonstration of how [Heroku Metrics](https://devcenter.heroku.com/articles/metrics), [Scout](https://elements.heroku.com/addons/scout), [New Relic](https://newrelic.com/) and [derailed_benchmarks](https://github.com/schneems/derailed_benchmarks) can be used to diagnose and resolve memory swapping caused by N+1 queries and why memory allocations should be front of mind. Maybe some Puma worker/thread memory tuning. Some introspection on how memory allocation affects response time, infrastructure load and some general performance ideas.

![heroku metrics](https://s3-ap-southeast-2.amazonaws.com/kangarooit.com/images/heroku-metrics.png)
![scout query analysis](https://s3-ap-southeast-2.amazonaws.com/kangarooit.com/images/n_plus_one_query.png)

**Comment by ceels** [comment]
Hi @jkotchoff Would you be interested in presenting a talk at the January RORO? We'll still be online. We've been finding that 20-30 minute talks or 5min lightning talks have been working well with the online format.

**Comment by jkotchoff** [comment]
Hey @ceels, sounds good. I'd probably be interested in the longer form talk.

**Comment by ceels** [comment]
Great! Looking forward to it. Do you have a preference for which talk to present?

**Comment by jkotchoff** [comment]
I'd like to do this performance talk first if that's ok.

**Comment by VanessaNimmo** [comment]
https://youtu.be/-o-HAQVDvJo
