### ISSUE TITLE
View Components in the Wild

### ISSUE THREAD

**Issue by saramic** [rails-oceania/melbourne-ruby#172]
Just some examples of how we at [Fresho](http://fresho.com) are using [View Components](https://viewcomponent.org/) to test rails views and help us decompose the front end, it will be wild! With the better design through composability, leading to simplifying testing and more consistent front ends.

inspired by https://github.com/rails-oceania/melbourne-ruby/issues/158

presented from https://github.com/failure-driven/view-components-in-the-wild

ready for Feb 2021 - ie like tomorrow

**Comment by VanessaNimmo** [comment]
https://youtu.be/ISWuPcCoChw 🌄
