### ISSUE TITLE
The Joy of Docs: Technical Writing for Developers and Engineers

### ISSUE THREAD

**Issue by danascheider** [rails-oceania/melbourne-ruby#173]
Hello organisers! I would like to propose a talk about technical writing. You can see the slide deck [here](https://docs.google.com/presentation/d/1somOY_01ZRgSxuAIX-RenImp9QkgytjpXwsKm91lYoo/edit?usp=sharing) if you'd like to suss it out more, but here's the gist. I can be available any Wednesday but need at least a few days' advance notice to let my D&D group know I won't be there :)

## Talk Title

The Joy of Docs: Technical Writing for Developers and Engineers

## Description

In this talk, I discuss communication, specifically technical writing, why it's important, and how to improve your skills. Emphasis is on identifying and empathising with your audience. The talk does not strictly cover the writing process as it is taught in schools, but rather focusses on orienting oneself towards readers' needs when writing technical documents or producing other technical writing. The information in this talk is applicable to any kind of technical writing, from commit messages to requests for comment (RFCs), as well as technical writing that is not strictly a part of a technical document (e.g., writing in an email to stakeholders about the status of development on a project). 

## Why It's Important

Bad technical writing is a huge waste of time. Every developer who's worked in the industry for any length of time has encountered vague and unhelpful documentation and seen how much time they spend trying to find information that should've been in the docs in the first place. Engineers who read RFCs and other longer-form documents may notice these documents often don't give adequate context or define terms, leading to more time spent on research rather than focussing on the tasks at hand.

**Comment by CumulusGround** [comment]
Hi Danna, 
Thank you for proposing this talk!

It sounds like a great talk and it's definitely already right at home with me :) :S

How long do you thing your talk would take? 
The next RORO is next wednesday the 31st of March.

Would you be keen/ready to present then?

Cheers

**Comment by danascheider** [comment]
The 31st works! The last time I gave this talk it ran about 30 minutes but I can make it longer or shorter to suit. Just let me know!

**Comment by CumulusGround** [comment]
awesome, 31st it is then.
We'll be in touch with you shortly

**Comment by CumulusGround** [comment]
https://youtu.be/l8pFr1y14f8
