### ISSUE TITLE
Exercism for Junior Developers

### ISSUE THREAD

**Issue by achhetr** [rails-oceania/melbourne-ruby#174]
Hi guys, I recently completed a bootcamp from Le Wagon. 

I have experienced that most bootcamp graduate lack the understanding of test driven development as well as how to conduct pair programming coding challenge. I would like to present 2 exercism exercise to showcase how to approach a problem.

I am also participating in the presentation to build confidence around technical gurus.

**Comment by CumulusGround** [comment]
Hey @achhetr, Thank you for reaching and well done for putting yourself out there!!
Would you be keen to Present at the April RORO on the 28th (next week)?
 How long would your talk be?
 
 Thank you

**Comment by achhetr** [comment]
Thank you @CumulusGround for giving me this opportunity. I am planning to give 15 to 20 mins talk. 
I have two ideas which I am happy to share with young developers. 
1) 2 exercism exercise to showcase how to approach a problem
2) How to integrate React with Rails

Please suggest which one should I go as I think they both are really important

**Comment by CumulusGround** [comment]
Hey @achhetr,

they do both sound great!!
but obviously I'm mindful of having a couple of speakers on the night.

How about this:
We can do React/Ruby this time
then skip next month
then have you back in June for the exersim one.

My thought behind it is that I think a lot of bootcamp just started in March and should wrap up in June, which theoretically would give us an influx of junior, perfect target crowd for the exercism.

what do you think?

Cheers

**Comment by achhetr** [comment]
Sounds great @CumulusGround

This will be my first presentation, have you got any tips which I can offer to the audience from React on Rails perspective
