### ISSUE TITLE
Lightning talk: How to stop I18n getting complex

### ISSUE THREAD

**Issue by davich** [rails-oceania/melbourne-ruby#175]
10 minutes. 
In Rails, I18n gets confusing :( I'm always trying to figure out where keys come from and what text methods return. 

My team and I have done some cool stuff to keep it simple. I've never seen it done like this before, so I'd like to share it.

**Comment by CumulusGround** [comment]
Hey @davich,

That sounds great.
Would you be willing to share at this month's RORO (30th June)?

Let me know

**Comment by davidcarlin-ap** [comment]
Yep, can do. Will it be in person or zoom?

**Comment by davich** [comment]
ha, that's also me ^^. On my work github account. Probably confusing to the casual observer.

**Comment by CumulusGround** [comment]
haha no problem @davich / @davidcarlin-ap.
do you have a title for your talk?

**Comment by davich** [comment]
yep, that's a descriptive title. Will the meetup be in person or zoom?

**Comment by CumulusGround** [comment]
Meetup will be over Zoom @davich 
:)
