### ISSUE TITLE
Data pipelines in Rails and Postgres

### ISSUE THREAD

**Issue by saramic** [rails-oceania/melbourne-ruby#176]
the nuts and bolts of how to insert and upsert data quickly in Rails and Postgresql using both the gem `activerecord-import` and Rails 6 new `insert_all` and `upsert_all` command. Also some thoughts on how to do data processing in Ruby using the chaining `then` to compose data transformations.

follow my progress on the talk here -> https://github.com/failure-driven/data-pipelines-in-ruby

should be good to go for July meetup

**Comment by CumulusGround** [comment]
Awesome @saramic, looking forward to hear about it.
I guess I'll ask you later on long you think this one will be  :)

**Comment by CumulusGround** [comment]
Hey @saramic,
Confirming you are all still good to present at this wednesday RORO ? 
:) 
See you then

**Comment by saramic** [comment]
yeah all good - probably be ~30min but will try to cut it shorter if I can

**Comment by CumulusGround** [comment]
no stress.
I'm still looking for a lighting talk contender !
