### ISSUE TITLE
Keith Pitt - Magic

### ISSUE THREAD

**Issue by quamen** [rails-oceania/melbourne-ruby#18]
@keithpitt is going to talk at the November meetup, actual content is still up on the air, but I'll leave it up to him to fill in the blanks :)

**Comment by keithpitt** [comment]
Ha! Awesome! I've got a few different things that I can talk about (depending on what people want to hear).

1. "How to travel the world and run a startup at the same time"
2. "GraphQL, Relay and React is the future of programming, for realz, don't care what you say, I will prove it"
3. "Race conditions are the worst" or "Why I spent all of my time in Croatia rewriting Buildkite"

That's all I've thought of for now :)

**Comment by ZimbiX** [comment]
Haha nice. I'd be keen to hear all three =)

**Comment by quamen** [comment]
I love a good rant, I vote for number 2.

**Comment by joneslee85** [comment]
:+1: for 2

**Comment by gerrywastaken** [comment]
How long can you speak for? 1, 2 and 3 in that order of preference.

**Comment by keithpitt** [comment]
@gerrywastaken for as long as necessary! :watch:
