### ISSUE TITLE
Talk proposal: Image compression. How it works, why you need it

### ISSUE THREAD

**Issue by davidcarlin-ap** [rails-oceania/melbourne-ruby#185]
It seems to be unclear who should be the expert on image compression. Engineers or designers? We all want fast sites and most of a site's download is in images, so this is fertile ground for optimisation.

I'd like to dig into different image formats and what they're good for. A bit of a deep dive into how some of the formats work (DCT, chroma-subsampling etc). And the future of images on the web.

20 minutes, maybe?

**Comment by optimistic-updt** [comment]
I'll pencil you in for Jan
