### ISSUE TITLE
Sebastian von Conrad - Practical TDD

### ISSUE THREAD

**Issue by quamen** [rails-oceania/melbourne-ruby#19]
@vonconrad is going to run an interactive session on TDD.

**Comment by bingxie** [comment]
Will you use Rspec or minitest?

**Comment by vonconrad** [comment]
@bingxie Rspec, but the testing framework used has very little meaning. I'm going to show the TDD practice, not a particular framework.

**Comment by vonconrad** [comment]
@quamen Any chance we can spell my name correctly in the title? :grin:

**Comment by quamen** [comment]
> @quamen Any chance we can spell my name correctly in the title?

@vonconrad suer thing ;)
