### ISSUE TITLE
Bronwen Clune & Jo Cranford - Diversity in Tech

### ISSUE THREAD

**Issue by jocranford** [rails-oceania/melbourne-ruby#21]
We would like to present some data from recent diversity studies carried out by Culture Amp alongside other research, to answer these questions: 
- Why is diversity more than just a pipeline issue?
- Why should we care?
- What are the different ways in which women experience the tech industry compared to men?
- What other groups have different experiences?
- How can your team be more inclusive?

**Comment by mariovisic** [comment]
This talk was great by the way!
