### ISSUE TITLE
require, load and autoloading in ruby as well as rails

### ISSUE THREAD

**Issue by mariovisic** [rails-oceania/melbourne-ruby#23]
I'd like to present on all the different ways that you can require external code in the ruby language. I've learnt a lot about this recently and I don't think it's that widely understood, but it's a good thing to learn.

I'll touch on the basics of the $LOAD_PATH and how require and load work. I'll talk a bit about ruby's inbuilt autoload and how it can be used for gem authors. I'll also talk a bit about rails's autoloading, which is different from rubys, i'll talk about how code is automatically reloaded in development between requests and the pitfalls of this.

**Comment by leriksen** [comment]
Great topic - almost enough for a series,  or a book!!

**Comment by mariovisic** [comment]
@quamen late notice, but i'm now going to be away in Perth all next week. Are you able to bump me to the following month? I'd also be OK with presenting remotely as well if you want to try that out!

**Comment by quamen** [comment]
@mariovisic moving you to March. Let me know if that's cool?

**Comment by mariovisic** [comment]
@quamen very cool!

**Comment by gerrywastaken** [comment]
A bit late for me to ask, but is this still happening tonight?

**Comment by mariovisic** [comment]
@gerrywastaken ah sorry, i've managed to end up in Perth again this week, but i'll be around next month to present. 

I believe @radar has organised a replacement, but i'm not too sure who will be presenting.

**Comment by radar** [comment]
I can't reassign the milestone, otherwise I would have already.

This talk is moved to April.

We'll be having Sebastian give a 40 min talk tonight which'll give us ample talk time tonight :)

**Comment by gerrywastaken** [comment]
Curse you again Perth! Cheers for the heads up @mariovisic
