### ISSUE TITLE
Lowering the Bar; a Diversity Myth

### ISSUE THREAD

**Issue by lengarvey** [rails-oceania/melbourne-ruby#24]
It's a commonly heard refrain that we can't get more women into jobs in our industry because we don't want to "lower the bar". I'd like to address this on several levels:

1. It's faulty logic.
2. It's faulty maths.
3. You don't know your own biases.

Finally I'd like to talk about some simple things we might be able to do.

I want to give this talk for a couple of reasons:

1. It's important to hear men valuing this kind of discussion. It shouldn't be always women or other under-represented groups fighting to be heard.
2. Hearing it from a man will, sadly, reach more men in our industry. I wish this wasn't the case but unconscious bias is a big deal. :sob: 

This talk is suitable for people of all levels. It's not about code, but there will be maths.

**Comment by quamen** [comment]
@lengarvey would you be able to give this talk next week? Turns out @mariovisic is in Perth.

**Comment by lengarvey** [comment]
👍🏼
No worries



On Thu, Feb 18, 2016 at 11:14 PM -0800, "Gareth Townsend" <notifications@github.com> wrote:












@lengarvey would you be able to give this talk next week? Turns out @mariovisic is in Perth.

**Comment by mariovisic** [comment]
Thank @lengarvey
