### ISSUE TITLE
Event Sourcing, part 2

### ISSUE THREAD

**Issue by vonconrad** [rails-oceania/melbourne-ruby#25]
I'd like to follow up my RubyConf talk which was meant to make people curious about Event Sourcing, with a talk about some of the practicalities and where to start.

For those who missed my RubyConf talk, I'll quickly recap that before launching into particulars.

I'd allow for 45 mins for this talk.

**Comment by joneslee85** [comment]
:+1:

**Comment by garrow** [comment]
:+1:

**Comment by xuebingli** [comment]
:+1:

**Comment by quamen** [comment]
@vonconrad are you happy to do this in March?

**Comment by vonconrad** [comment]
For sure!

**Comment by quamen** [comment]
Locked in 😄👌🏼

**Comment by vonconrad** [comment]
Awesome! Thanks @quamen. :smile:
