### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by vonconrad** [rails-oceania/melbourne-ruby#26]
I have an idea for a talk about Dependencies. It would be aimed at beginners and intermediate developers and discuss what dependencies are and how they work. We'll draw them and talk through what circular dependencies are and how (and why) to avoid them.

Probably 20-30 mins.

**Comment by Ashley-Pettit** [comment]
I'd love this talk. Definitely had issues with dependancies and would love to hear what you have to say about it!

**Comment by quamen** [comment]
@vonconrad how would you feel about giving this talk in October?

**Comment by vonconrad** [comment]
@quamen Could do! I need an excuse to put the slides together for this one anyway, as I've been meaning to give it internally at Envato as well.

**Comment by quamen** [comment]
@vonconrad consider yourself locked in for October then :)

**Comment by vonconrad** [comment]
:+1:

**Comment by quamen** [comment]
@vonconrad just checking you're still good to talk on Wednesday?

**Comment by vonconrad** [comment]
I've been sick all weekend so prep time has been close to zero. I should be able to get something together though.

**Comment by quamen** [comment]
@vonconrad 👌
