### ISSUE TITLE
Philosophy of Affirmative Action, Ruby in Emacs, Electrocution Driven Development

### ISSUE THREAD

**Issue by duncan-bayne** [rails-oceania/melbourne-ruby#28]
I'd love to give a talk on April that's really three back to back lightning talks, with Q&A:

 * The philosophy of affirmative action (how AA is built upon the same philosophical principles as irrational discrimination, and why that's a problem) 
 * Ruby in Emacs (cool Emacs plugins and config to make Ruby hacking awesome) 
 * Electrocution Driven Development (in which I demo a hardware rig and a custom RSpec formatter that shocks you once per failing test; an audience volunteer will be called for) 

I anticipate it'll be around 15 minutes long in total plus Q&A, ranging from non-technical to quite deep. Plus electrocution, that's always good fun.

**Comment by duncan-bayne** [comment]
See https://mobile.twitter.com/duncan_bayne/status/702463858519121920 for the inspiration for EDD.

**Comment by drej2k** [comment]
I'm interested in ruby in emacs.  

Would be good for Vim users and sublime users too add they can see if they can add that type of functionality to their ide of choice

**Comment by quamen** [comment]
Locked in for May

**Comment by duncan-bayne** [comment]
@quamen I'll have you know I stayed up until midnight last night polishing this presentation, so I could make the date!!!!

Actually that's a total lie :smile:.  I stayed up until midnight in a mental haze from too many cold drugs, and finished the presentation on the train this morning.  Scheduling it for May will also give me the time to measure the current output from the EDD rig; when hooked up to a developer with ECG patches it causes involuntary muscle activation so it's a bit stronger than I'd originally planned.

Turns out that datasheets for $1 joke pens are hard to obtain ...

**Comment by duncan-bayne** [comment]
Sorry again for not being able to present this last month :cry: 

@quamen Can we slot this presentation in sometime in the next few months?

**Comment by quamen** [comment]
@duncan-bayne June is full, and July is scheduled to be a ruby noobie night. Does August work for you?

**Comment by duncan-bayne** [comment]
Thanks for getting back so promptly - unfortunately not, as my wife will be 8 months pregnant at that point & she's specifically asked me to be at home evenings by then.

November??? Is it too early to schedule that?

**Comment by quamen** [comment]
> November??? Is it too early to schedule that?

nope. I'll create a mileston and assign it.
