### ISSUE TITLE
Rebuilding citizenship in the 21st century

### ISSUE THREAD

**Issue by alvaromaz** [rails-oceania/melbourne-ruby#30]
Democracy is rooted in the idea that government derives its power from citizens, and that citizens are a necessary participant in building strong government. But in an age of deep cynicism in the political process, record low voter turnout and historic mistrust in government, we have lost that sense of civic responsibility.
Digital technology offers an opportunity to reanimate citizenship for the 21st century, making government work for and, more importantly, by the people again.
Alvaro will talk about Code for Australia's work creating spaces for productive citizen participation, where we can use not just our voices but also our hands to build more responsive governments and ultimately a stronger democracy.

**Comment by quamen** [comment]
@alvaromaz how long will this presentation be roughly?

**Comment by alvaromaz** [comment]
sorry forgot to add this - 15-20 minutes

**Comment by quamen** [comment]
Would you be able to give this talk in June?

**Comment by alvaromaz** [comment]
Hey Gareth - yes, I see you have a hack night on the 8th? Let me know the
date and i'll put it in my calendar

Alvaro

**Comment by quamen** [comment]
@alvaromaz talks will be on the 29th of June (last Wednesday of the month). Let me know if that suits you and I'll lock the talk in.

**Comment by alvaromaz** [comment]
I might have to get my other co-founder and director to do this one. His
name is Dan Groch - I've cc'ed him here. He's definitely in.

**Comment by dgroch** [comment]
Yep, happy to do this. 
Where can I find all the details, eg location, date, start time?

**Comment by quamen** [comment]
@dgroch the details for the June meetup can be found here: http://www.meetup.com/Ruby-On-Rails-Oceania-Melbourne/events/230893256/

**Comment by dgroch** [comment]
Thank you @quamen

**Comment by quamen** [comment]
@dgroch just confirming you're still good to talk in June?

**Comment by dgroch** [comment]
Yep, will be ready to talk on the 29th :)
