### ISSUE TITLE
Maintaining legacy Rails applications

### ISSUE THREAD

**Issue by asadeghi** [rails-oceania/melbourne-ruby#31]
I'd like to present on my experiences maintaining a legacy customer facing Rails application. We all know how to build an app, but keeping one up to date, or trying to resuscitate it after it has been ignored for 5+ years is a bit of a battle. I gather more and more organisations are having to deal with this legacy Rails app cost and hopefully I can empower them with some tips on how to reduce the pain.

I recently had the 'pleasure' of updating an old application I co-wrote (https://cobalt.offbyzero.com), so I will base the talk on direct experience from that effort. I haven't written the talk yet, but expect it to be intermediate level and about 20 minutes long.

**Comment by quamen** [comment]
Would you be able to give this talk in June?

**Comment by asadeghi** [comment]
Absolutely. Would that be June 29th?

**Comment by quamen** [comment]
@asadeghi yes, that would be the 29th of June

**Comment by asadeghi** [comment]
Thanks @quamen. I'll get it ready for then.

**Comment by quamen** [comment]
@asadeghi just confirming you're still good to talk in June?

**Comment by asadeghi** [comment]
Yes indeed. Thanks for checking Gareth.

**Comment by asadeghi** [comment]
Hi @quamen. Apologies again for not being able to present my talk in June. Can I please be rescheduled for an upcoming month? I can do July or any other month that suits you. Cheers.

**Comment by quamen** [comment]
@asadeghi We're running a noobie night this month, would this talk be suitable for beginners as a talk towards the end of the night? Or do you think it would go well over their heads. I ask as it's currently tagged as intermediate.

**Comment by asadeghi** [comment]
@quamen . Now that I have written the talk I can see that it is closer to beginner level, so would be quite appropriate for noobies. I probably also only have 15 minutes of material. Would be happy to go at the end of other talks this month. Feel free to update labels (doesn't look like I can do that myself). Cheers.

**Comment by quamen** [comment]
@asadeghi awesome. In that case I'll get you to speak this month and we'll slot you in towards the end as one of the slightly longer talks.

**Comment by asadeghi** [comment]
@quamen Sounds good.
