### ISSUE TITLE
Recording RoRo presentations

### ISSUE THREAD

**Issue by duncan-bayne** [rails-oceania/melbourne-ruby#32]
Not a presentation, but an offer from Cogent of sponsorship, by way of recording presentations and making them available online through Eventer:

https://www.eventer.com/

If people are interested in proceeding, I'll arrange to set up the equipment with the Teamsquare folks, and it should hopefully be ready to record by the May presentation.

**Comment by quamen** [comment]
Thanks for the offer. As long as we're happy to allow presenters the option of opting out, this sounds good to me 👍 

Lets try it out in May and see how the community reacts.

**Comment by duncan-bayne** [comment]
Actually, looks like May might not work; I'll keep you posted as soon as I know more.
