### ISSUE TITLE
Ruby Newbies talks, July

### ISSUE THREAD

**Issue by gusseting** [rails-oceania/melbourne-ruby#33]
Proposal: 5 min talk on Mentoring: What newbies are looking for + need in mentors, from a newbie perspective.

**Comment by MelissaKaulfuss** [comment]
Proposal: 30 minute Q&A lead panel discussion with a varied set of people who are at different stages of their journeys as junior devs. 

Involving topics such as:
– How did you land your first job as a junior? 
– What was involved in the hiring process?
– 3 tools/thing-ys you use everyday at work and you think any junior should learn to help their chances.
– 2 years on – what you should know and be doing to continue developing your career.

Something along those lines?

**Comment by drej2k** [comment]
@MelissaKaulfuss How is this going? 
Would love to get involved, help out and present my experiences. Let me know...

**Comment by quamen** [comment]
@drej2k I've heard from @MelissaKaulfuss that the panel isn't going to happen, but would be very keen to have you do a talk on something. 

Maybe a 5 minute lightning talk on something interesting in ruby/rails? 

I'll be giving my intro to enumerable talk for example.

**Comment by drej2k** [comment]
@quamen i could do a 5 min talk on git using tig (recovering from doom - quickly restoring to previous project states)

But I can only present prior to 7.30pm. I have to leave by 7.45pm.

Otherwise I am happy to present next month, on a different topic, for a longer timeframe and something that might be a junior/mid level talk. 

Let me know what works.

**Comment by quamen** [comment]
@drej2k 5 minutes on git and how to save yourself from doom sounds great. We'll put you up first.

**Comment by drej2k** [comment]
@quamen Ok, I better start writing this talk!

**Comment by quamen** [comment]
@gusseting are you still good to talk on mentoring?

**Comment by gusseting** [comment]
@quamen indeed!

**Comment by Ashley-Pettit** [comment]
Heya, I can if needed :). Looks like starting a dev job and would love to share what worked/what didn't when learning. Chaio!

**Comment by quamen** [comment]
@Ashley-Pettit consider yourself signed up 👍
