### ISSUE TITLE
API Docs - Like a boss!

### ISSUE THREAD

**Issue by rpocklin** [rails-oceania/melbourne-ruby#34]
This would be a 5 - 10 minute summary of how to auto-generate current API docs that deploy with your code, and make it look at sweet as Stripes - https://stripe.com/docs/api/python#metadata

Let me know if you want this for the 29th of June.

**Comment by quamen** [comment]
Sounds like a fantastic talk.

We've already got a full line up for June. I'll confirm with the other speakers and get back to you.

**Comment by quamen** [comment]
@rpocklin would this talk be suitable for beginners? Or more tailored towards intermediate/advanced ruby developers?

**Comment by quamen** [comment]
@rpocklin would you be able to do this talk at the August meetup?

**Comment by quamen** [comment]
@rpocklin or even at the September meetup?

**Comment by kirikamal** [comment]
Sounds good

**Comment by rpocklin** [comment]
Apologies, can't do the September one - October is perfect though.

**Comment by quamen** [comment]
@rpocklin October it is then

**Comment by quamen** [comment]
@rpocklin just checking you're still good to talk on Wednesday?

**Comment by rpocklin** [comment]
Yep

**Comment by rpocklin** [comment]
Yep
