### ISSUE TITLE
Hiring Strategies and Best Practices To Scale Your Dev Team

### ISSUE THREAD

**Issue by martinli11** [rails-oceania/melbourne-ruby#35]
What has Hired seen in terms of data across the globe for Ruby developers? What are the trends developing for Ruby developers globally and in Australia?

In today's competitive hiring environment, what are some best practices and strategies to get the most out of your teams? What is the key to hiring well, and hiring fast so you can be first to go to market with your product?

Speaker will be Sascha Gray, Head of ANZ for Hired.

More info on Hired: http://bit.ly/1UXYM3k

**Comment by sniferx1** [comment]
+ 1 from me

**Comment by quamen** [comment]
@martinli11 would you be able to give this talk at the September meetup?

**Comment by martinli11** [comment]
@quamen What date exactly is the September meetup? I will confirm with Sascha but should be no problem!

**Comment by quamen** [comment]
@martinli11 it will be the Wednesday the 28th of September.

**Comment by martinli11** [comment]
@quamen Yup can do, lock it in!

**Comment by Ashley-Pettit** [comment]
Will be an interesting talk. I'd like to know how is hired is different to a recruitment agency. The fees still seem very high

**Comment by martinli11** [comment]
@quamen FYI - we are going to bring in Andrew Erskine for this talk. He has been with Hired since the beginning and is in charge of the "talent" side of our business. He will bring specific insights for Melbourne market (as well as global trends) that will be particularly relevant for the audience!

**Comment by quamen** [comment]
@martinli11 sounds good to me 👍
