### ISSUE TITLE
Crystal for Ruby developers

### ISSUE THREAD

**Issue by anicholson** [rails-oceania/melbourne-ruby#39]
Hi!

I've been using [Crystal][crystal] for a small side project and would like to share a bit about the language to Ruby developers :)

[crystal]: http://crystal-lang.org/

**Comment by gerrywastaken** [comment]
I'm so glad there is somebody else out there who sees it's potential. I would love to hear this talk.

**Comment by quamen** [comment]
@gerrywastaken would you be able to do this talk at the August meetup?

**Comment by anicholson** [comment]
@quamen I'm going to assume you meant me! I can probably make that work :)

**Comment by quamen** [comment]
@anicholson oh yes, I definitely meant you 😄

**Comment by gerrywastaken** [comment]
@quamen @anicholson I had a slight panic attack 😆

**Comment by anicholson** [comment]
[Deck from the talk][1]

[1]: http://andrewdotni.ch/presentations/crystal-roro-aug-2016/
