### ISSUE TITLE
Speeding up CI with parallel-rspec & aggressive caching

### ISSUE THREAD

**Issue by mipearson** [rails-oceania/melbourne-ruby#40]
I'd like to talk about how we use buildkite, aggressive asset caching and parallel-rspec to achieve a 5x to 10x speedup on our integration testing stack at Marketplacer.

I'd also like to talk a bit about our integration testing strategy and how it allows us to confidently deploy to production on any green build, and why that means that a fast CI system is essential for our team.

**Comment by quamen** [comment]
Love it!

**Comment by mipearson** [comment]
Yep, I'd love to. Transport issues mean that I would greatly prefer to be the first slot, though.

**Comment by quamen** [comment]
@mipearson the first slot is yours then

**Comment by sniferx1** [comment]
+1 for this topic
