### ISSUE TITLE
GitSavvy - change how you work with Git

### ISSUE THREAD

**Issue by jocranford** [rails-oceania/melbourne-ruby#41]
GitSavvy is a Sublime text plugin that changed my life. Seriously, it's that good. I've been using it for over a year and it's crashed maybe once. 

It integrates with Sublime to allow you to create commits and view diffs. If you don't love working with the command line, but find GUI tools a bit cumbersome, GitSavvy is like the perfect mix. 

I would like to do a short talk to demo the tool (probably with slides / videos not live demo). If the Aug meet up is the 31st please can it be September?

**Comment by quamen** [comment]
Locked in for September @jocranford

**Comment by quamen** [comment]
@jocranford I'm going to close this as you're unavailable to give the talk for the rest of the year. If things change, or you want to do this talk next year, just re-open the issue.
