### ISSUE TITLE
Writing a Gameboy Emulator in Ruby

### ISSUE THREAD

**Issue by colby-swandale** [rails-oceania/melbourne-ruby#42]
Hi, I will be giving this talk at RubyKaigi in September and would love to show everyone here in Melbourne as well.

Released in 1989 the Gameboy was the first handheld console of the Gameboy series to be released by Nintendo. It featured games such as Pokemon Red & Blue, Tetris, Super Mario Land and went on to sell 64 million units worldwide.

My talk will be discussing what components make up a Gameboy, such as the CPU, RAM, Graphics and Game Cartridge. How each component works individually and how they work together to let trainers catch em all. Then how to replicate the behavior of the Gameboy in code to eventually make an emulator.

Here is the project page: https://github.com/colby-swandale/waterfoul

**Comment by quamen** [comment]
@colby-swandale Love it.

**Comment by joneslee85** [comment]
❤️

**Comment by colby-swandale** [comment]
I should mention that you don't require a computer science degree to understand my talk, i have made it very friendly and accessible to everyone. If you understand basic ruby such as arrays and loops, you're all good.

**Comment by quamen** [comment]
@colby-swandale I've tagged this talk as a beginner friendly talk. Would you be happy to do this at our September meetup (28th) which is after RubyKaigi?

**Comment by colby-swandale** [comment]
sounds good 👍

**Comment by quamen** [comment]
@colby-swandale locked in.
