### ISSUE TITLE
Improve perceived performance of your rails application with minimum effort

### ISSUE THREAD

**Issue by antulik** [rails-oceania/melbourne-ruby#43]
I've finally extracted library from the work project.

https://github.com/antulik/pagelet

Would like to present on subject of perceived performance and demo proposed solution. The talk would interesting for all levels of developers. 

Would like to present on August meetup while the knowledge is still hot. Flexible on time, but need to know the length of the talk beforehand.

**Comment by quamen** [comment]
@antulik sounds good to me. How long do you want to talk for?

**Comment by antulik** [comment]
20-30 min

**Comment by quamen** [comment]
@antulik awesome. You're locked in for August.
