### ISSUE TITLE
Writing Observers

### ISSUE THREAD

**Issue by alexiamcdonald** [rails-oceania/melbourne-ruby#44]
I thought I could do a talk about writing observers in Rails. It would be aimed at beginners. The talk would probably be about 15 minutes.

**Comment by quamen** [comment]
@alexiamcdonald would you like to give this talk in October?

**Comment by alexiamcdonald** [comment]
Yeah sure

**Comment by quamen** [comment]
@alexiamcdonald 👏

**Comment by quamen** [comment]
@alexiamcdonald just checking you're still good to talk this Wednesday?

**Comment by alexiamcdonald** [comment]
@quamen I haven't finished it but if it doesn't pan out I can always do the one I did at the Elixir meet

**Comment by quamen** [comment]
> @quamen I haven't finished it but if it doesn't pan out I can always do the one I did at the Elixir meet

@alexiamcdonald 👌
