### ISSUE TITLE
November - lightning talks only

### ISSUE THREAD

**Issue by antulik** [rails-oceania/melbourne-ruby#46]
November meetup should only has lightning talks. Each 5 minutes maximum, no slides required. You can talk about anything - ruby, favourite gem or just what you've worked on or learned during the year.

If you come to meetup be prepared to talk about something. You might not have a chance, but if asked you should talk. No exceptions.

Why
- this was the successful format of BrisRuby and Railcamps for multiple years 
- last meetup of the year is perfect to be summary of the year
- encourages new speakers from community
- big variety of talks
- maximum 5 minutes duration is widely accepted 
- good to experiment in the community

**Comment by quamen** [comment]
I love this idea.

**Comment by MelissaKaulfuss** [comment]
I could quickly cover:
3 things I've learnt in my first 3 months as a dev.
(something along those lines – but it will be ruby focused).

**Comment by drej2k** [comment]
@antulik Thanks for proposing this. Worked out really well!

**Comment by antulik** [comment]
Yeah it worked amazingly well. Thanks to @quamen 

We should do it more often like @quamen suggested.
