### ISSUE TITLE
Rack Fundamentals

### ISSUE THREAD

**Issue by simonhildebrandt** [rails-oceania/melbourne-ruby#49]
Learn the machinery that underpins our favourite frameworks, and why you might not need a whole Rails stack for an API that's basically a single method.

Potential lightning talk, or 20 minute full presentation.
- Simon Hildebrandt is a senior web developer with extensive experience in Ruby and Javascript, and has written or contributed to several Ruby gems and NPM modules.

**Comment by quamen** [comment]
@simonhildebrandt lets do this talk in January

**Comment by simonhildebrandt** [comment]
Awesome, sounds good. :)
