### ISSUE TITLE
Restroom: API Gems The Easy Way

### ISSUE THREAD

**Issue by simonhildebrandt** [rails-oceania/melbourne-ruby#50]
While trying to improve on the existing Bitbucket gem, we stumbled on this one weird trick for building gems for RESTful APIs.

https://github.com/simonhildebrandt/restroom

Potential lightning talk, or full presentation.
- Simon Hildebrandt is a senior web developer with extensive experience in Ruby and Javascript, and has written or contributed to several Ruby gems and NPM modules.

**Comment by tcn33** [comment]
@simonhildebrandt thanks for giving this talk on short notice last meetup :)

**Comment by simonhildebrandt** [comment]
My pleasure. :)
