### ISSUE TITLE
Beyond Heroku: Amazon Opsworks for Ruby and Rails

### ISSUE THREAD

**Issue by simonhildebrandt** [rails-oceania/melbourne-ruby#51]
Somewhere between the cookie-cutter simplicity of Heroku and the land of web-scale industrial Docker, I found a sweet spot for prototyping and rapidly evolving systems - Amazon's Opsworks. Learn about the features and workflows that make this platform a great choice for new-to-mid-level projects.

Potential lightning talk, or full presentation.
- Simon Hildebrandt is a senior web developer with extensive experience in Ruby and Javascript, and has written or contributed to several Ruby gems and NPM modules.

**Comment by VanessaNimmo** [comment]
Hey @simonhildebrandt - is this still a relevant talk for you and for RORO?
