### ISSUE TITLE
Grape with Swagger: effortless, self-documenting APIs

### ISSUE THREAD

**Issue by simonhildebrandt** [rails-oceania/melbourne-ruby#52]
Learn the simplest way to wire up a RESTful API in Ruby - and the one weird trick to automatically generate interactive documentation for it.

Potential lightning talk, or full presentation.
- Simon Hildebrandt is a senior web developer with extensive experience in Ruby and Javascript, and has written or contributed to several Ruby gems and NPM modules.

**Comment by quamen** [comment]
@simonhildebrandt would you be available to give this talk in March?

**Comment by simonhildebrandt** [comment]
Wait... I never actually gave this one, did I? I did Restroom?

**Comment by tcn33** [comment]
I thought you did this one a few months before Restroom... or am I confusing this with something else? You did the lightning talk in November that (I think) covered Restroom a little, then I thought you did Swagger in Jan or Feb. No?

**Comment by quamen** [comment]
I think you did restroom, twice. I don't remember a talk on swagger at all.

**Comment by tcn33** [comment]
I stand corrected then :)

**Comment by simonhildebrandt** [comment]
Goodness, I repeated myself? That's embarrassing... OK, well a Swagger one still makes sense then...

**Comment by tcn33** [comment]
@simonhildebrandt Want to do this one May 31st?

**Comment by simonhildebrandt** [comment]
Sure, sounds good.

**Comment by tcn33** [comment]
@simonhildebrandt just confirming we're still good for this Wednesday?

**Comment by simonhildebrandt** [comment]
Totes - have already done practice runs for my cow-orkers. :)

**Comment by fbvilela** [comment]
@simonhildebrandt the video is up https://youtu.be/-agspVmHrKg
good work!!

**Comment by fbvilela** [comment]
@tcn33 Feel like sending an email to the list? 

Ruby meetup 31/05/2017 - All the 3 talks are now on Youtube
https://www.youtube.com/watch?v=_S3mAnfGqGQ
https://www.youtube.com/watch?v=wAMryNKuSIY
https://www.youtube.com/watch?v=-agspVmHrKg

**Comment by tcn33** [comment]
Can do :)

On Thu, Jun 1, 2017 at 4:19 PM, Fabio Vilela <notifications@github.com> wrote:
@tcn33 [https://github.com/tcn33] Feel like sending an email to the list?

Ruby meetup 31/05/2017 - All the 3 talks are now on Youtube
https://www.youtube.com/watch?v=_S3mAnfGqGQ [https://www.youtube.com/watch?v=_S3mAnfGqGQ]
https://www.youtube.com/watch?v=wAMryNKuSIY [https://www.youtube.com/watch?v=wAMryNKuSIY]
https://www.youtube.com/watch?v=-agspVmHrKg [https://www.youtube.com/watch?v=-agspVmHrKg]

**Comment by tcn33** [comment]
Thanks @simonhildebrandt :D
