### ISSUE TITLE
React-ion Time Is A Factor: Ultralight web applications with React

### ISSUE THREAD

**Issue by simonhildebrandt** [rails-oceania/melbourne-ruby#53]
Learn why Facebook's framework for web interfaces makes the difficult trivial and the impossible merely awkward - with tips on asset pipelines and modern JS development (ES6, Browserify) and hints about complimentary technologies (MaterialUI, GraphQL, RxJS.)

Potential lightning talk, but better as a full presentation.
- Simon Hildebrandt is a senior web developer with extensive experience in Ruby and Javascript, and has written or contributed to several Ruby gems and NPM modules.

**Comment by VanessaNimmo** [comment]
Hi @simonhildebrandt - is this still a talk you'd like to give at RORO?
