### ISSUE TITLE
Open Source: Power and the Passion

### ISSUE THREAD

**Issue by pat** [rails-oceania/melbourne-ruby#55]
This is a talk I've given at a few conferences, about the pros and cons of open source, how we've built so much on top of it, but it's perhaps not the stable foundations we were hoping for.

It's not been accepted for RubyConf AU, so I'm happy to present it at RORO at some point :) It's about 30 minutes long.

**Comment by quamen** [comment]
@pat awesome, would January or February work for you?

**Comment by pat** [comment]
January works for me :) (February too, but it'll be a little fresher in my mind in Jan).

**Comment by quamen** [comment]
Lets lock it in for the January meetup then.

**Comment by pat** [comment]
@quamen sorry to throw a spanner in the works, but I've _just_ been asked to be a backup speaker (with this presentation) for RubyConf AU. Potentially giving the same talk twice in the same city within a couple of weeks feels unwise… is it possible to find a replacement speaker for the Jan meetup? Happy to be a potential speaker for Feb (if I'm not called upon at the conference).

**Comment by quamen** [comment]
@pat Boo! Hiss! 😛 😃 

It's all good. We still have 2 speakers lined up for January so I'll just shift your talk to Feb/March or sometime later based on whether you give the talk or not at RubyConf AU.

**Comment by pat** [comment]
Thanks Gareth :)

**Comment by pat** [comment]
So I did end up speaking at RubyConf AU, and I think the moment's passed for having this talk at Melbourne Ruby. I'll ponder topics for future presentations though!
