### ISSUE TITLE
Quitting your job as a responsible Melbourne Rubyist

### ISSUE THREAD

**Issue by ponny** [rails-oceania/melbourne-ruby#56]
More coherent version of my 4.5 minute lightning talk but with pacing, slides, gifs, and maybe graphs this time.  Happy to delay it for a while until it feels fresh.

Talking points: 
1. The fallacy of the startup
2. Bootstrapping and the Monthly Recurring Revenue metric
3. Moonlighting and how to find the time
4. Competitive advantages/disadvantages of being a Melbournian, a Rubyist, and an Australian
5. Your ideas are probably terrible
6. Co-founders and equity

No code, probably 20-30 mins.

**Comment by yifeiwu** [comment]
I like this

**Comment by quamen** [comment]
@ponny would you be able to give this talk at the March meetup?

**Comment by ponny** [comment]
@quamen Sorry, I missed your message in my firehose of GitBub spam ;-)

Can do.

**Comment by quamen** [comment]
Not too late. Lets lock it in 😄

**Comment by ponny** [comment]
Going to have to re-schedule, sorry.

**Comment by tcn33** [comment]
@ponny are you available to give this talk at the next RORO on May 3rd?

**Comment by ponny** [comment]
@tcn33 Yep.  Planning on it.

**Comment by ponny** [comment]
Had a chat to reschedule on 3rd with Gareth.  Sorry that wasn't clear.

**Comment by tcn33** [comment]
@ponny boom! Thank you :)

**Comment by ponny** [comment]
Slides: https://bit.ly/quitrmr

**Comment by radar** [comment]
@fbvilela @ponny wants to know if his talk was recorded too. He said to me:

> Was my talk actually recorded and simply not put live?  If so, I’d be happy to have it up now that I know it isn’t an embarrassment

I'm sure he can confirm by commenting on here too.

**Comment by fbvilela** [comment]
Hi @ponny, 

Your talk was recorded and it was great! I just didn't edit it...  (yet)
I'll go ahead and post the link in here. hold on tight. Then you can send it to the whole rails-oceania list

**Comment by fbvilela** [comment]
here @ponny 

https://youtu.be/jSJD2He23-U it's live!

**Comment by ponny** [comment]
@fbvilela Looks and sounds really good.  Great work.
