### ISSUE TITLE
Real-world i18n

### ISSUE THREAD

**Issue by ponny** [rails-oceania/melbourne-ruby#57]
Our journey to 27 languages and the steps we wish we took.

Contents: 
1. Setting i18n up Rails
2. Useful tooling
3. What we did wrong
4. Getting translations
5. Maintaining translations
6. Right-to-left, long words in Russian, and other edge cases to drive you mad

Some code, ~15 mins

**Comment by quamen** [comment]
@ponny would you be available to give this talk in Feb?

**Comment by ponny** [comment]
I'd prefer not this month.  There's a talk that sounds very similar at RubyConf Melbourne 2017.

**Comment by quamen** [comment]
@ponny no worries, we'll wait till after RubyConf and figure out a date then
