### ISSUE TITLE
Code forensic analysis

### ISSUE THREAD

**Issue by smontanari** [rails-oceania/melbourne-ruby#58]
This is a presentation/demonstration talk about alternative techniques to analyse large codebases and detect potential issues with software design or code quality. I'm going demo the use of [code-forensics](https://github.com/smontanari/code-forensics) as applied to our rails monolith in Redbubble and how it is helping us to address the growing technical debt. The work is inspired by the book "Your Code as a Crime Scene" by Adam Tornhill.

The talk is for all levels and my purpose is to get more people interested and engaged in using code-forensics to make it a complementary instrument next to more traditional static code analysis tools.
20~30 mins

**Comment by quamen** [comment]
@smontanari would you be available to give this talk in Feb?

**Comment by smontanari** [comment]
Yes I would, any time you like

**Comment by quamen** [comment]
@smontanari lets lock this one in for Feb then 😄

**Comment by fbvilela** [comment]
https://youtu.be/cv-Az03TBbI
@smontanari @quamen 

Here is the recording. Video is unlisted for now.

Gareth, let's talk about creating the melbourne ruby youtube channel and upload the videos as public

**Comment by quamen** [comment]
@fbvilela is there anything special I need to do to set this up? or do I just create an account and invite you?

**Comment by tcn33** [comment]
@smontanari excellent talk :)
