### ISSUE TITLE
Building consistent developer environments

### ISSUE THREAD

**Issue by mcgain** [rails-oceania/melbourne-ruby#59]
At Shopify, we've used Boxen and Vagrant, and then finally developed our own set of tools to manage development environments. I want to share our journey and hopefully offer some advice for people wanting to build their own.

I want to cover:
* Why even use environment configuration
* The advantages and disadvantages of Vagrant, Boxen, and Babushka
* How we developed dev(our tool), why we chose to build our own, and the benefits and drawbacks
* Running in virtual machines vs running on the host
* What will go wrong (spoiler alert: everything)

Full talk. Is 20 mins the standard time? There will be a little code shown, but not code heavy by any means. Probably not that good for beginners though.

**Comment by quamen** [comment]
@mcgain sounds like a great talk. I've tagged this as 20minutes and targeted at intermediate developers. 

Would you be able to give this talk in Feb or March?

**Comment by mcgain** [comment]
@quamen Yeah, Feb or March would be fine.

**Comment by quamen** [comment]
@mcgain I'll lock you in for a talk in Feb then 😄

**Comment by fbvilela** [comment]
Hi @mcgain , @quamen 
It's the first time I edit a video like this... I have uploaded as unlisted.
Our recording system produces two files, the slides and the stage video, in synch, which is pretty cool. See what you guys think of it and I'll edit the other two talks tomorrow. 

https://www.youtube.com/watch?v=dNuTj0WMpuc&feature=youtu.be
video might be still processing... give it a few minutes.

**Comment by mcgain** [comment]
Thanks!

The recording seems to have worked out pretty well. A couple of audio issues where I lean away from the mic, but there's nothing you can do about that.

**Comment by tcn33** [comment]
Great talk @mcgain :)
