### ISSUE TITLE
git init – a beginners guide to untangling source control

### ISSUE THREAD

**Issue by MelissaKaulfuss** [rails-oceania/melbourne-ruby#60]
I've done this talk at campJS it seemed to be well received.
It's very beginner focused. 
Talks through the very basics of how git works.
I might add some more stuff now that I have some experience untangling things a bit more.

I really don't want to bore everyone though if it's too basic. I feel like this is good for someone who has no idea what and why they'd use it.

**Comment by MelissaKaulfuss** [comment]
@quamen can you tell me is this scheduled at all? I just need to know if I have to write a talk.

**Comment by quamen** [comment]
@MelissaKaulfuss this is not currently scheduled, but if you're available to do this talk in March then I'll schedule it. Let me know.

**Comment by MelissaKaulfuss** [comment]
Nah all cool, happy to wait it out ;)

**Comment by VanessaNimmo** [comment]
Closing this issue as @MelissaKaulfuss can no longer make RORO 😢
