### ISSUE TITLE
Shrine – Handle File Uploads like it's 2017

### ISSUE THREAD

**Issue by janko-m** [rails-oceania/melbourne-ruby#61]
[Shrine](https://github.com/janko-m/shrine) is a relatively new solution for handling file uploads, which I've been actively developing for over 1 and a half years. I've built Shrine because the existing libraries were missing many features that I considered essential for creating great user experience around file uploads, and I would love to share them with you.

Things that I would cover:

* Direct uploads using AJAX
* Handling file processing in the background
* Resumable uploads
* Performance comparisons with other file upload libraries
* Demo application

The goal of this talk is for people to learn more about good practices for handling file uploads, and to demonstrate how easy it is to implement more advanced workflows using Shrine.

This talk would target mainly intermediate/advanced level folks, though I intend to briefly introduce concepts for the novice crowd. I think this would be more like a 40min than 20min, but if you accept only 20min talks I could definitely adjust 😃. Also, I'm available for the February meetup (later my visa expires, so I wouldn't make it for the March meetup).

**Comment by quamen** [comment]
@janko-m sounds like a great talk, lets lock it in for Feb

**Comment by fbvilela** [comment]
https://youtu.be/plD-RkKEay0
@janko-m @quamen 

Here's the video of the talk...

**Comment by janko-m** [comment]
@fbvilela Great, thank you!
