### ISSUE TITLE
On the Roda 'gain: beautiful Rack routing

### ISSUE THREAD

**Issue by anicholson** [rails-oceania/melbourne-ruby#62]
Having used Roda a couple times recently and _loved_ it, I'd be happy to share an example on how to get going and set up Roda for clarity and joy :)

Level: Beginner-Intermediate
Time: ~20 minutes

Not going to be available before April :)

**Comment by quamen** [comment]
> Not going to be available before April :)

Sounds good to me, can I lock you in for May?

**Comment by anicholson** [comment]
@quamen which week of May will it be? I'm going to be away at the start. If it's in the final 2 weeks I can do it :)

**Comment by quamen** [comment]
@anicholson Wednesday the 31st of May

**Comment by anicholson** [comment]
@quamen lock it in, Eddie :)

**Comment by tcn33** [comment]
@anicholson are you still ok to present this on May 31st?

**Comment by anicholson** [comment]
@tcn33 should be! Better start writing it :P

**Comment by anicholson** [comment]
@quamen / @tcn33 I'm _really_ sorry to do this, but I got home from holidays on Sunday to find that I'd been broken into and my laptop was pinched. My backups don't go quite far forward enough, so I'll have to postpone :(

**Comment by tcn33** [comment]
@anicholson no drama! This is why we have backups :)

**Comment by tcn33** [comment]
@anicholson still interested in doing this one? How about October?

**Comment by anicholson** [comment]
@tcn33 I could – what day would that be?

**Comment by VanessaNimmo** [comment]
Hi @anicholson - is this still a talk you'd like to give at RORO?

**Comment by anicholson** [comment]
@VanessaNimmo RORO's still a Wednesday, right? If so, I'll have to put it on ice as I live in Bendigo and I'm not normally in Melbourne on a Wednesday :(

**Comment by VanessaNimmo** [comment]
@anicholson It is still a Wednesday. No plans to change it at present, so I'll close this issue. You should bring it to the Unconference at the next Rails Camp!
