### ISSUE TITLE
Why you should stop using Slack

### ISSUE THREAD

**Issue by keithpitt** [rails-oceania/melbourne-ruby#63]
Probably a bad title to choose, but the talk will be about other methods of communication, and what the world was like pre-slack, and how real-time ASAP collaboration may be doing you more harm than good.

Talk will be around 10-15 minutes. There won't be any code.

Available when evs!

**Comment by quamen** [comment]
@keithpitt would you be available to give this talk in March?

**Comment by keithpitt** [comment]
@quamen sure thing! What date?

**Comment by quamen** [comment]
@keithpitt 29th March.

**Comment by keithpitt** [comment]
@quamen rad, I'll be there!

**Comment by antulik** [comment]
@keithpitt are the slides available?

**Comment by keithpitt** [comment]
@antulik they're not I'm afraid :( I don't think I'll post them because there wasn't a great amount of detail in them - just funny pictures. 

My entire talk was pretty much a poor recreation of the points in this blog post: https://m.signalvnoise.com/is-group-chat-making-you-sweat-744659addf7d if you read that you'll get the gist of what I was talking about :)

**Comment by tcn33** [comment]
Loved your work :)

**Comment by keithpitt** [comment]
Thanks @tcn33! A+, would rant again!
