### ISSUE TITLE
How to cloud – a beginners guide to AWS

### ISSUE THREAD

**Issue by MelissaKaulfuss** [rails-oceania/melbourne-ruby#64]
Would like to cover the basics of:
What is cloud, what you can do with AWS, services they provide, costs.
EC2
ELB
Auto-scaling

I have no fucking idea but I will have an idea by the time I give this talk (if you let me).
Let's schedule this for May if you want to let me.

**Comment by quamen** [comment]
@MelissaKaulfuss lock it in 😄

**Comment by MelissaKaulfuss** [comment]
Okay 👍

**Comment by kirikamal** [comment]
For May

**Comment by tcn33** [comment]
@MelissaKaulfuss this is scheduled for May 31st - are you still ok to present then?

**Comment by MelissaKaulfuss** [comment]
@tcn33 no, I'm afraid I won't have time, I have 2 talks to give this month and will need to write them sorry. Can I request this be delayed? Sorry.

**Comment by tcn33** [comment]
@melissakaulfuss No problem. July maybe?

**Comment by MelissaKaulfuss** [comment]
Yeah sounds good!! Lock it in @tcn33 🔒

**Comment by tcn33** [comment]
@MelissaKaulfuss did you get a chance to put this together? Or did you have another you'd like to do?

**Comment by MelissaKaulfuss** [comment]
Hiya 

Nope,  Might close this issue. Too much going on right now :(

**Comment by pauloancheta** [comment]
I could give this talk if it's open. 

I can also give: 
- introduction to CloudFormation
- IAM roles
- brief explanation of differences in EC2's

Maybe if we have enough time I can expand to ELB and ASG as well.

**Comment by VanessaNimmo** [comment]
Hey @pauloancheta - is this still something you are interested in presenting?

**Comment by pauloancheta** [comment]
Hi @VanessaNimmo! I just moved back to Canada so I won't be able to present this anymore

**Comment by VanessaNimmo** [comment]
Wow! Seems fair 😂
