### ISSUE TITLE
The long road to Internet 

### ISSUE THREAD

**Issue by MelissaKaulfuss** [rails-oceania/melbourne-ruby#66]
A non-codey talk about my path into dev.
What happened when I got there.
How I struggled with imposter syndrome and anxiety and overcame it.

Light, and not too long, runs about 10-15 mins.

**Comment by quamen** [comment]
@MelissaKaulfuss are you happy to give this talk this month?

**Comment by MelissaKaulfuss** [comment]
Yeah okay I'll do it 💯

**Comment by quamen** [comment]
👏

**Comment by tcn33** [comment]
Great talk :)
