### ISSUE TITLE
About product design sprints

### ISSUE THREAD

**Issue by elle** [rails-oceania/melbourne-ruby#67]
- What they are
- What they are good for
- Who should be involved
- What do they entail
- What do you get in the end of the sprint

**Comment by tcn33** [comment]
Hey @elle - would you be available to give this talk at the next meetup (May 3rd)? Sorry for the late notice :(

**Comment by elle** [comment]
Of course

**Comment by tcn33** [comment]
Awesome, thanks @elle!

**Comment by fbvilela** [comment]
Thanks @elle . I have recorded and edited your talk. It's live!!
https://www.youtube.com/watch?v=9J2nvU36vpE&feature=youtu.be

if, for any reason, you don't want this to be live, just let me know. 
if you're happy, would be good if you could send the link to the whole rails-oceania folks :) 

Thanks,
Fab

**Comment by tcn33** [comment]
Thanks @elle, great talk!
