### ISSUE TITLE
Step away from ActiveRecord

### ISSUE THREAD

**Issue by HashNotAdam** [rails-oceania/melbourne-ruby#68]
I've just refactored a method so that a task which used to take several minutes instead takes seconds.

Previously, the heavy lifting done by the method was performed in Ruby which was replaced with SQL. It's a great example of how sometimes it can be valuable to sacrifice the many benefits of an ORM for the raw performance of SQL.

While the time for this talk can be flexible, I would suggest it may be better to keep it on the shorter side since the content could be pretty heavy for the more junior members.

**Comment by simonhildebrandt** [comment]
That sounds awesome. 😊

**Comment by tcn33** [comment]
@hashnotadam are you available to give this talk tomorrow night? Sorry for the late notice, we had a last-minute cancellation

**Comment by HashNotAdam** [comment]
@tcn33 Sorry, not enough notice, particularly since I've only just seen your message. I need to create a couple of clear slides so I'm not just dropping a stack of SQL on people 😆

**Comment by tcn33** [comment]
@HashNotAdam no drama, very short notice. May 31 perhaps?

**Comment by HashNotAdam** [comment]
Lock it in @tcn33, that's more than enough time to ensure it isn't a total snooze-fest

**Comment by HashNotAdam** [comment]
@tcn33 can you let me know how long you'd like this?

**Comment by tcn33** [comment]
@HashNotAdam let's say 20 min?

**Comment by tcn33** [comment]
@HashNotAdam just confirming we're still good for this Wednesday?

**Comment by HashNotAdam** [comment]
@tcn33 I'm all good to go

**Comment by fbvilela** [comment]
@HashNotAdam https://youtu.be/_S3mAnfGqGQ it's live!
share around!

**Comment by simonhildebrandt** [comment]
Cool! Do we have one coming for my presentation too?

**Comment by fbvilela** [comment]
off course @simonhildebrandt , I'm editing it at this exact moment... uploading Lauren's now...
will paste your link in your github issue.

**Comment by simonhildebrandt** [comment]
Awesome, thanls @fbvilela . :) (Didn't know I was being filmed. :D )

**Comment by HashNotAdam** [comment]
Thanks for all your work, @fbvilela

@simonhildebrandt, stop being so vain; if you're so eager to look at yourself, find a mirror 😆

**Comment by simonhildebrandt** [comment]
LOL - I'm not satisfied with the editing of Lauren's talk - you can barely hear me at all. :D

**Comment by HashNotAdam** [comment]
Opens new issue: ensure @simonhildebrandt is microphoned at all times.

**Comment by fbvilela** [comment]
That's why we ask to repeat the question on the mic... 
But I will ask IT if we can have the spare mic going around for the questions ;) 

it's a valid point hehehe

**Comment by HashNotAdam** [comment]
Really glad I listened to that recording; it became clear why you need to repeat the questions as well as the need to not turn away from the mic.

**Comment by tcn33** [comment]
Great talk Adam, thanks for doing it!
