### ISSUE TITLE
Yet another walkthrough on Hanami 1.0

### ISSUE THREAD

**Issue by joneslee85** [rails-oceania/melbourne-ruby#69]
![](http://hanamirb.org/images/home-background.jpg)

[Hanami framework](http://hanamirb.org/) has just released [its 1.0](http://hanamirb.org/blog/2017/04/06/announcing-hanami-100.html), marking the biggest milestone ever achieved by this humble project with an ambition to offer to Web-based app Ruby developers an alternative to Rails.

There has been many changes in the core of the framework and I think it might be a good opportunity to re-do the same talk I did a year a go on [intro to Lotus (former name of Hanami)](https://github.com/rails-oceania/melbourne-ruby/issues/16).

I would try to do following within the time limits:

* Core concept about Hanami
* Offer analogies to Rails for your consideration
* Try to answer questions about Hanami (if you have any)

Lastly, Hanami is a very young project, it has its edges and I am sure some of early adopters might have been cut. So I hope to receive constructive feedbacks from you if you have been using it.

![](http://hanamirb.org/images/logo.png)

**Comment by radar** [comment]
@joneslee85 Are you prepped to give this talk next week?

**Comment by joneslee85** [comment]
@radar if I get chosen, surely I will

**Comment by tcn33** [comment]
@joneslee85 you're chosen! Still good to go for May 3rd?

**Comment by joneslee85** [comment]
@tcn33 hey Toby, I am not in good shape to give presentation tomorrow. Sorry for the last minute change, I'll give this talk next month.

**Comment by tcn33** [comment]
@joneslee85 okay for the May 31st meetup? (it's _almost_ next month 😝 )

**Comment by joneslee85** [comment]
@tcn33 sorry for late reply, this talk would be best on July. I will re-open the issue next month.
