### ISSUE TITLE
All your Firebase are belong to us

### ISSUE THREAD

**Issue by simonhildebrandt** [rails-oceania/melbourne-ruby#70]
Everyone's trying to sync their data into their browser interfaces - graphql, pubnub, web sockets... But what if all the heavy lifting was done for you, and you could just respond to library events, on the server *and* the browser? Firebase is a new Google acquisition that has wide-ranging integrations across services like authentication, and languages like Ruby - and with integrated security tools, you might not even *need* a server...

**Comment by simonhildebrandt** [comment]
Simon Hildebrandt is a senior web developer with extensive experience in Ruby and Javascript, and has written or contributed to several Ruby gems and NPM modules.

**Comment by simonhildebrandt** [comment]
(This could be a lightning talk, or a more involved 20-minuter.)

**Comment by HashNotAdam** [comment]
Agreed 👍

**Comment by simonhildebrandt** [comment]
Firebase has no offline development option, pushing me towards other options - when I've nailed an alternative down I'll raise it as an alternative approach.
