### ISSUE TITLE
The biggest cause of bugs in your application: `git commit`

### ISSUE THREAD

**Issue by michaeldawson** [rails-oceania/melbourne-ruby#71]
Every line of poor quality code, every late-night screw-up, every bug that brought down production... can usually be traced back to one command: `git commit` (that is, unless you don't use git 😃)

How can we use git to reduce the number of bugs that make it into our applications? Covering interactive staging, commit structuring, fixup commits, git hooks and pull requests, this talk is for developers that use git every day to ship their code, but want to improve their code quality and rigour through their git workflow.

Excuse the TL;DR factor, but here's an overview of what I'd cover in a 20 minute presentation:

* Staging changes:
  - The importance of interactive staging
  - Trick to add all files (including new files) with interactive staging
  
* Committing changes:
  - Commits are sacred - give them the respect they deserve!
  - Let's talk about commit messages, commit content, pre-commit hooks, and crafting branches

  * Commit messages:
    - Shoddy and fragmented commit messages often go hand-in-hand with shoddy and fragmented code
    - Imperative case, consistency (no period at the end), etc
    - Multi-line commit messages are good for changes that have some complexity!

  * Commit content:
    - More important than the message is the actual commit content
    - Commits should have content that matches their message. Don't sneak in unrelated changes.
    - Be standalone and self-contained (allowing for rolling back)
    - Have both code and tests
    - Choosing to be rigorous here forces the quality of our code up, it's not just about being dogmatic

  * Pre-commit hooks
    - Since git commit is the gateway for code to get into our application, we want to put up defences here!
    - Overcommit as a tool for running automated checks against commit contents
    - Rubocop for ruby linting, Reek for ruby smells (optional), ESLint for JS linting, etc

  * Crafting branches
    - Why build branches for all features and fixes
    - How crafting self-contained and well-structured branches makes bugs much more obvious, and how sloppy branches swallow bugs
    - Staying in touch with what's in your branch is very important: enter aliases `git ls` (List Short) and `git lsb` (git List Short, for this Branch)
    - `git commit --amend` and `git commit --fixup`, how they work with `git lsb`
    - squashing fixup commits
    - yes, I'm a rebaser, and I recommend it, but I understand the case for merging
    - you can use fixup commits with shared branches! 
    - the golden rule of editing git history is not to do things that require force pushing to shared branches
    - alias `git hard-pull` for easier working with force pushed branches (which must always be communicated and kept to a minimum)
    - Committed something that belongs in another branch? No problem! `git cherry-pick`, and `git rebase` to remove it from your current branch

* In pull requests / reviews
  - The pull request is another very important step in our git workflow for catching bugs
  - Always request a review - it can be brief, but another set of eyes is very important
  - No-one is above the need for review (don't let your managers get away with it!). It's also good for knowledge sharing
  - Github and Bitbucket's automation hooks for running CI
  - With hound, the same linting can be run in CI as you run locally with overcommit
  - If you don't currently run any tests CI, at least come up with a few mission-critical acceptance tests that can be run with every build

Bonus: some more fun and handy git aliases.

**Comment by tcn33** [comment]
@michaeldawson looks great :) are you able to do this one at the June meetup?

**Comment by michaeldawson** [comment]
Sure! Would love to :)

**Comment by tcn33** [comment]
@michaeldawson we have had a cancellation - if you're able to do this on short notice we'd love to have you present it on the 31st 🤞

**Comment by michaeldawson** [comment]
Sorry for the late reply - I could do that, would be a bit of a stretch, but if you still need me, let me know and lock it in 👍

**Comment by radar** [comment]
I think we're good now, thanks though :) we'll put you down for June?

**Comment by michaeldawson** [comment]
Ok, nice! Yep, let's aim for June.

**Comment by tcn33** [comment]
@michaeldawson just confirming you're still ok for June 28?

**Comment by michaeldawson** [comment]
@tcn33 Yep, I'll be there.

**Comment by michaeldawson** [comment]
So this talk could push 30 minutes if time allowed for that. Is there any flexibility there?

**Comment by tcn33** [comment]
@michaeldawson yep, we'll have you go first and whip through the intro stuff so you get going as early as possible :)

**Comment by fbvilela** [comment]
@michaeldawson the talk is live https://youtu.be/JSfjV6-IAjQ
nice work!! loved it!

**Comment by tcn33** [comment]
Thanks @michaeldawson - I learned a lot :)
