### ISSUE TITLE
How to pair-program effectively

### ISSUE THREAD

**Issue by elle** [rails-oceania/melbourne-ruby#72]
- either with peers or more importantly with juniors
- will go over:
  - the psychology of what both sides might think or feel when we pair (mindset and language used, empathy, guidelines about asking questions)
  - the etiquette of pairing (i.e. no keyboard hogging, no social surfing)
  - how to pair without exhausting yourself
  - ideal desk set up for pairing (lowest denominator of text editor)
  - techniques (for example ping-pong pairing)
  - tools for remote pairing

**Comment by tcn33** [comment]
Hey @elle - looks great! How long are you thinking for this one?

**Comment by elle** [comment]
@tcn33 15-20 minutes

**Comment by tcn33** [comment]
@elle are you available to do this talk at the next meet up? (June 28th)

**Comment by elle** [comment]
@tcn33 sorry, no can do. Meet up after that??

**Comment by tcn33** [comment]
@elle just wanted to check if July 26th is still ok for this talk?

**Comment by elle** [comment]
@tcn33 yes, it is

**Comment by tcn33** [comment]
@fbvilela just wanted to check if recording went ok for July's talks?

**Comment by fbvilela** [comment]
@tcn33 .... sad news. the next day when I asked for the recording, IT told me that the files were not there. We ran a couple of tests and it all went OK. I did nothing wrong, but we ended up with no recordings :(

We ran the Melbjs meetup where I was also the one to record and everything went OK. 
so yeah, we try again next time

**Comment by tcn33** [comment]
Oh, that’s a shame. Next time :)
