### ISSUE TITLE
Place Month tag on talks in github to show month when they will be presented at RubyMelb

### ISSUE THREAD

**Issue by drej2k** [rails-oceania/melbourne-ruby#73]
Thanks for publishing the talks that are occurring at tonights RubyMelb on meetup.com
I was about to ask if this can be done :smile: 

Additionally, could we place a month tag, against the github issue, on each proposed talk? 
I would find this useful so that I could see the planned talks for the coming months. 
Might also set a convention so that future talk proposals specify a month for their talk, making talk to month allocation self sustaining. :smile:

**Comment by drej2k** [comment]
I see that some talks have a month allocated but most do not...
Also I find the current date allocation difficult to read, not easy to scan for.

**Comment by tcn33** [comment]
@drej2k at the moment we're using milestones for month allocation. This lets us see at a glance how many talks we have allocated for each month. 
<img width="994" alt="screen shot 2017-05-31 at 5 01 01 pm" src="https://cloud.githubusercontent.com/assets/7378906/26619667/c29a8e86-4622-11e7-8310-7f5866209f11.png">
It shouldn't be relied on though as talks for each month aren't finalised until (at most) a week prior to each RORO. 

If you want to submit a talk and choose the month to deliver it, that's fine by us :)
