### ISSUE TITLE
GraphQL for fun and profit

### ISSUE THREAD

**Issue by tomjadams** [rails-oceania/melbourne-ruby#74]
There's a lot of interest in GraphQL, from people with all sorts of language backgrounds. I gave this talk in Sydney at APIDays (https://www.infoq.com/presentations/graphql-intro), and would be keen to do it again for a local audience. 

I've found that when I've given this talk most of the good stuff comes from questions. You can dig right into the queries and show people how things work, try different use cases, etc.

**Comment by tcn33** [comment]
@tomjadams we'd love to have you do this on June 28th, if you're available.

**Comment by davich** [comment]
Do it @tomjadams ! 👍

**Comment by tomjadams** [comment]
I can make that @tcn33.

Thanks for adding the tags too, I didn't seem to be able to!

**Comment by tcn33** [comment]
@tomjadams just confirming you're still ok for June 28?

**Comment by tomjadams** [comment]
@tcn33 Yep, but I'll need to bring my kids, will that be a problem?

**Comment by tcn33** [comment]
No problem at all.

**Comment by fbvilela** [comment]
Talk is live https://youtu.be/Tub3XMumQvA
thanks @tomjadams ! it was awesome! Say hello to Filippo ;)

**Comment by tcn33** [comment]
Thanks @tomjadams, really enjoyed it!
