### ISSUE TITLE
Meta presentation

### ISSUE THREAD

**Issue by antulik** [rails-oceania/melbourne-ruby#75]
In this talk I will share hints how to do amazing presentation slides with code in keynote. The presentation will be around 10 minutes.

**Comment by tcn33** [comment]
@antulik want to do this one for June 28th? :)

**Comment by antulik** [comment]
yes, sounds good

**Comment by tcn33** [comment]
@antulik still ok for June 28?

**Comment by antulik** [comment]
Yes

**Comment by fbvilela** [comment]
@antulik it's live https://youtu.be/UEqm8lAaF8s
it was awesome! thanks for that!

**Comment by tcn33** [comment]
Thanks @antulik - great talk!
