### ISSUE TITLE
My favourite command line tools

### ISSUE THREAD

**Issue by compactcode** [rails-oceania/melbourne-ruby#77]
I'd like do a talk about three of my favourite command line tools (`ripgrep`,`fzf` & `fasd`).

My plan is to introduce the unix philosophy of single purpose, modular programs and then show how we can apply that philosophy to combine these three tools in interesting ways to:

Find projects
Find files
Find directories
Search files
Find git branches

The talk would be aimed at the junior/intermediate level and I can make it either 10 or 20 mins long.

**Comment by tcn33** [comment]
@compactcode thanks for submitting this :) Is this talk ready now or do you need some prep time?

**Comment by compactcode** [comment]
@tcn33 need a bit of prep time :)
