### ISSUE TITLE
How Does Bundle install Work?

### ISSUE THREAD

**Issue by colby-swandale** [rails-oceania/melbourne-ruby#78]
Bundler is part of every ruby developers workflow but have you ever wondered how Bundler takes your Gemfile and figures out exactly what version of your dependencies and their dependencies you need? How Bundler knows which of your gems are hosted where.

I want to give a 30 min talk that will explain the major concepts of how Bundler works, things like the Index, dependency API,  RubyGems.org, Version resolution.

This talk will be intermediate.

Thanks.

--
Disclaimer: I'm a core developer of Bundler and this talk will be adapted from a series of blog posts that i'm working on.

**Comment by tcn33** [comment]
Hey @colby-swandale sounds great! Is it ready to go for June or July, or do you need some time?

**Comment by colby-swandale** [comment]
I'm good with July if that's open

**Comment by tcn33** [comment]
@colby-swandale still good for July 26th?

**Comment by colby-swandale** [comment]
Yep

**Comment by colby-swandale** [comment]
Hey @tcn33, sadly i can no longer attend next week, i need to duck off to wagga wagga but i can book August if available. Sorry! 🙇

**Comment by tcn33** [comment]
No drama, will move you across to August. Cheers :)

**Comment by tcn33** [comment]
@colby-swandale still on for August 30th?

**Comment by colby-swandale** [comment]
yep! no last minute trips either this time 👍

**Comment by tcn33** [comment]
Thanks Colby!
