### ISSUE TITLE
Functional affairs in Ruby

### ISSUE THREAD

**Issue by jayzz55** [rails-oceania/melbourne-ruby#79]
Recently, there has been a buzz about FP (Functional Programming), and there has been a lot of Rubyist start exploring FP languages like Elixir, Clojure, Scala, and Haskell.

In this talk, I'd like to present about what's the buzz with FP, Why we care about FP, and ultimately how do we apply this FP Concept back in our day to day code as a Rubyist.

This talk will be in 2 parts:
* **Part 1** will be Beginner - Intermediate level and will take 20 minutes.
In Part 1, we will venture into the Functional aspects of Ruby to do things like Lambda, Higher Order Function, Currying, and Composition.
* **Part 2** will be Intermediate level and will take 20 minutes.
in Part 2, we will venture into How we can apply these FP techniques, using libraries like [Transproc](https://github.com/solnic/transproc), [Dry Monads](https://github.com/dry-rb/dry-monads), and [Dry Transaction](https://github.com/dry-rb/dry-transaction). With this knowledge and tools, we will look at how we can apply FP pattern such as [Railway Oriented Programming](http://fsharpforfunandprofit.com/rop/) on daily problems that we are solving as Rubyist.

Thanks.

**Comment by radar** [comment]
Hey @jayzz55, this sounds like a great idea for a talk. Would it be possible for you to make it 20-30 minutes though? 40 minutes seems a bit long for an evening talk and you might struggle to maintain people's attention for that long.

**Comment by jayzz55** [comment]
@radar I'm just concerned that cutting it to 20-30 minutes will leave people puzzled and confused when I go through Dry Transaction and Dry Monads without properly explain the basic block of using Ruby to do FP stuff.

**Comment by radar** [comment]
@jayzz55 Consider making it two talks then. Think of them as "part 1" and "part 2"?

**Comment by jayzz55** [comment]
@radar Good Idea 👍 

I'll see if I can cut my talk to max 30 minutes, if that's not possible, then I'll do part 1 and part 2 instead.

**Comment by tcn33** [comment]
@jayzz55 when would you like to do Part 1? At this point I can put you down for August 30th (and/or as a backup for July 26th)

**Comment by jayzz55** [comment]
@tcn33 I can do Part 1 for August 30th.

**Comment by tcn33** [comment]
@jayzz55 still on for August 30th?

**Comment by jayzz55** [comment]
Yes Toby, I'm good for 30th august

**Comment by fbvilela** [comment]
@tcn33 @jayzz55 https://youtu.be/TMCzv1fJ8yU !!
Tobi, see how good is to have to other mics for questions! This is the first time the new setup works.

**Comment by jayzz55** [comment]
@fbvilela Thank you for uploading this. the video and audio editing is great! 👍

**Comment by tcn33** [comment]
Thanks everyone!
