### ISSUE TITLE
Your story matters.

### ISSUE THREAD

**Issue by ridget** [rails-oceania/melbourne-ruby#80]
Hi :) 

As a co-organiser of the Brisbane Ruby Meetup, one of the things I often hear is "I don't have anything interesting to say" when I'm looking for talks for the month. 

I want to dive in and challenge that idea by identifying what it is about stories that are important to us, why your story matters and why you should tell it at the next Meetup. 

This talk will be looking at:
* Identifying what makes a good story
* Why does a good story make for a good talk.
* Why its important you share yours.
* How to find your own story.
* Why even stories without a happy ending are important to hear.

Can give this talk at the August Meetup as I'm in town for a couple of weeks then if the schedule allows.

**Comment by tcn33** [comment]
@ridget awesome! How long do you think your talk will go?

**Comment by ridget** [comment]
@tcn33 would 20-30min be ok? Happy to work to your schedule

**Comment by tcn33** [comment]
@ridget still on for August 30th?

**Comment by ridget** [comment]
@tcn33 absolutely :)

**Comment by tcn33** [comment]
@fbvilela how did the recording go? 🤞

**Comment by fbvilela** [comment]
@tcn33 great!!! I'm going to edit them soon

**Comment by fbvilela** [comment]
@tcn33 @ridget https://youtu.be/nChKjkG2NDw !!!!

**Comment by tcn33** [comment]
Thanks @ridget, such a pleasure to have you in Melbourne :)
