### ISSUE TITLE
Functional affairs in ruby part 2

### ISSUE THREAD

**Issue by jayzz55** [rails-oceania/melbourne-ruby#82]
Recently, there has been a buzz about FP (Functional Programming), and there has been a lot of Rubyist start exploring FP languages like Elixir, Clojure, Scala, and Haskell.

In this talk, I'd like to present about what's the buzz with FP, Why we care about FP, and ultimately how do we apply this FP Concept back in our day to day code as a Rubyist.

This is the part 2 of the talk given in Ruby meetup in August.

Part 2 will be Intermediate level and will take 20 minutes.
in Part 2, we will venture into How we can apply these FP techniques, using libraries like [Transproc](https://github.com/solnic/transproc), [Dry Monads](https://github.com/dry-rb/dry-monads), and [Dry Transaction](https://github.com/dry-rb/dry-transaction). With this knowledge and tools, we will look at how we can apply FP pattern such as [Railway Oriented Programming](http://fsharpforfunandprofit.com/rop/) on daily problems that we are solving as Rubyist.

**Comment by tcn33** [comment]
@jayzz55 are you available to do this talk in January? (31/1)

**Comment by tcn33** [comment]
@jayzz55 I'd love to get this talk on the schedule. January or February perhaps?

**Comment by jayzz55** [comment]
@tcn33 Hi Toby, apology for the late response.

I can do February if that's good for you.

**Comment by fbvilela** [comment]
https://youtu.be/OoXLy5tg9rw
