### ISSUE TITLE
A Programmer's guide to Van life

### ISSUE THREAD

**Issue by crunchysoul** [rails-oceania/melbourne-ruby#84]
**this is not a tech orientated talk**
**content is subject to change**

### Plan:
- share my experiences as a programmer who live in a camper van
- why conjunction of programmer and van dweller implies awesome
- the challenges, how to tackle them
- get started quick guide to Pro*Van life, where * = grammer

**Please feel free to comment, and/or chat with me, thank you.**

@crunchysoul

**Comment by davich** [comment]
I'd be super keen to hear this talk!

**Comment by radar** [comment]
Hey @crunchysoul do you want to do this talk for our October meet? That’ll be on the 25th of this month.

**Comment by crunchysoul** [comment]
Hey Ryan,

I love to prepare for the talk, thank you for your invitation, let me know any criteria that I should follow or just general rules for the talk, cheers.

Chen @crunchysoul

**Comment by radar** [comment]
No particular criteria. Just try to keep it to under 20-25 minutes.

**Comment by radar** [comment]
@crunchysoul Just checking: are you ready (or almost ready) to give this talk on Wednesday?

**Comment by crunchysoul** [comment]
Dear Ryan & Ruby community,

I’m extremely sorry for this delayed response.

My talk has already been prepared, but unfortunately I have been sick and laying in bed for past three days due to the flu.

It seems unrealistic for me to attend tonight's meetup and share the talk, as:

	1. may spread flu to other Rubyists;
	2. compromise quality of talk;
	3. less ideal physical condition;

May I apply to postpone my talk if future opportunity is available.

I genuinely apologise for any inconveniences cause by my short notice. I appreciate your understanding and support of the community.

Yours,
Chen @crunchysoul

**Comment by radar** [comment]
No worries @crunchysoul! We'll bump you to November. I'll do my coding test talk tonight :)

**Comment by tcn33** [comment]
@crunchysoul are you still ok to give this talk on the 29th?

**Comment by crunchysoul** [comment]
Dear Toby,

If the spot is still open, I would love to deliver the presentation, Cheers

Regards,
Chen @crunchysoul

**Comment by fbvilela** [comment]
https://youtu.be/TvY7LJ6l3Mo
