### ISSUE TITLE
Rails anti-patterns

### ISSUE THREAD

**Issue by elle** [rails-oceania/melbourne-ruby#85]
Learn about code smells that are more Rails-specific and their solutions. For example:
- Fat models
- Spaghetti SQL
- Callbacks
- Convoluted views
- Fat Controllers
- Monolithic controllers
- Sluggish services
- Failure to respond

**Comment by radar** [comment]
Hey @elle, do you want to give this talk at October’s meet?

**Comment by elle** [comment]
Hey @radar no can do. Am away for conferences then. Can do November though...

**Comment by radar** [comment]
No worries I will put you down for November

**Comment by tcn33** [comment]
@elle just confirming you're still good for the 29th?

**Comment by elle** [comment]
@tcn33 Yep

**Comment by sergio-weploy** [comment]
@elle Thanks for the talk!

I'm very interested in learning more about anti-patterns in Rails.  

1. Can you recommend a good learning resource?
2. Is the "Rails anti-patterns" book by Chad Pytel still relevant today (Rails 5)?

**Comment by fbvilela** [comment]
https://youtu.be/fU-mPNd-3AI
