### ISSUE TITLE
Designing the perfect coding test

### ISSUE THREAD

**Issue by radar** [rails-oceania/melbourne-ruby#86]
When interviewing candidates for a programming job a meet & greet doesn't cut it: we need to evaluate their coding ability too. But then what coding test should you give a candidate? Scrabble? The Game of Life? The Toy Robot? Calculating if a word is an anagram of another word? Are we even testing on the right things?

I'd love to give a talk on how I designed a coding test from scratch at Culture Amp and how I used it to evaluate people's competencies when it came to Ruby. (It may not have been as perfect as the provocative title suggests). I want to talk about how we built a little process around fairly grading those who submitted the coding test and also how we chose to give feedback to the candidates later on.

**Comment by fbvilela** [comment]
Sounds great! 👍 
can't wait!

**Comment by drej2k** [comment]
hey @radar @fbvilela, I unfortunately missed rubyMelbourne on Wednesday. Was the talk recorded? :smile:

**Comment by radar** [comment]
Yes I believe it was. @fbvilela will know for sure.

**Comment by fbvilela** [comment]
Yes @drej2k @radar . The talks were recorded and got lots of praise. 
I should edit them and paste their link in here.

**Comment by drej2k** [comment]
Great, thanks gents :smile:

**Comment by fbvilela** [comment]
@radar @drej2k @tcn33 
here's the first one https://youtu.be/DiYjDHKSH-Q
