### ISSUE TITLE
Story telling for your codebase with Git, Git Flow & Advanced Git

### ISSUE THREAD

**Issue by drej2k** [rails-oceania/melbourne-ruby#87]
### Hello
The high level aim of this talk is to share my experience as a starting point but learn from each other by creating a discussion so we can share all of our experiences collectively. 
(Yes a talk is usually a one way street, and some it will be, but I will try my best get some discussion happening 😄 )

### The Talk
I would like to talk about three main points:
1. Story telling: How Git can be used as a story telling mechanism for our code-base. 
2. The recipe: Git flow
3. The ingredients: Advanced Git

#### Point 1 - Story Telling
Explores  how Git can help us tell a story about our code. 
How we can achieve this without worrying or disrupting our flow? 
How can we improve how our commits tell a story?
What benefits can it bring?

#### Point 2 - The recipe
Will look at how we can put ourselves into a position so that we can curate our commits, reorganise, rework them in order to create a nice git log.

#### Point 3 - The ingredients
Concentrates on the tools that help us make the story happen. We commit but most of the time it is out of order or garbage and thats OK because we have the tools to fix it!

### Details
1, Collaboration friendly work-flows: (beginner)
- ' Flow' working in happiness & optimal concentration by not worrying
- Sizing a task (breaking it down to a feature)
- Benefits of breaking a feature into smaller ideas
- Sculpturing git commits so they are readable
- Sculpturing your git commit log so its a story
- Using your change log as a table of contents
- Enabling new/existing team members to familiarise themselves with the code base/pull request from a story perspective

2. Git Flow (mid level)
- What is not Git Flow (how to work in a non Git flow committing manner)
- What is Git Flow
- Why bother with Git Flow?
- Rebasing vs Merging
- We can Git Flow, so what? (the power of dealing with your problems yourself)

3. Advanced Git features: (mid+)
 - Renaming already committed commit messages
 - Splitting already committed commit into multiple smaller commits
 - Altering the code of already committed commits
 - Squashing commits
 - Finding where your code breaks using bisect
 - Bringing back a deleted commit or branch 
 - Extras: 
   - cloning from a local repository
   - collaborating from a local network repository

### Help!
Yes there are quite a few things in this talk. 
The three ideas are actually all connected towards the theme of creating a story for your code via Git, hence the desire to present them together. 
However, it might be too long, so I am open to concentrating on the aspects people find most interesting. 
So please take a look at the points and let me know!

### Duration
Duration: 25min (I cannot see this being a quick one!)

### Presentation Month
I am optimistically aiming for November (if there is room to present and more importantly I finish the talk) otherwise first month next year will be great!

**Comment by jayzz55** [comment]
Sounds like an amazing talk, looking forward to this talk! :)

**Comment by fbvilela** [comment]
https://youtu.be/7Zv3-h2AFKw
