### ISSUE TITLE
regex in ruby

### ISSUE THREAD

**Issue by MelissaKaulfuss** [rails-oceania/melbourne-ruby#88]
A deep or shallow dive into the ruby's Regexp class.
- How lazy vs greedy regex's work under the hood
- A few fun features to help you use regex effectively.

Aimed at beginners.

**Comment by tcn33** [comment]
@MelissaKaulfuss how long do you need?

**Comment by MelissaKaulfuss** [comment]
20-25 minutes so I can add a tad more?
This one was 15 mins :)

Happy to stick to that limit?

**Comment by tcn33** [comment]
@fbvilela how'd the recording go?

**Comment by fbvilela** [comment]
Hey @tcn33 it recorded alright. I didn't have time to edit it yet... but should be up in the next few days

**Comment by fbvilela** [comment]
https://youtu.be/dU97L1Jrji8 The recording took a while. . sorry :p
