### ISSUE TITLE
Exploring Enumerable Magic

### ISSUE THREAD

**Issue by apalski** [rails-oceania/melbourne-ruby#89]
Learn more about Ruby enumerables:
* why we use enumerables
* return values
* Boolean and search enumerables
* A look at some of the lesser used enumerables

**Comment by tcn33** [comment]
hey @apalski! Are you available to give this talk at November's meetup (the 29th)?

**Comment by apalski** [comment]
Hi Toby

I'm out for November I'm sorry, I will be on the high seas until
mid-December.

I'm happy for you to slate me in for the new year if that is ok.

Cheers Annette

**Comment by tcn33** [comment]
@apalski hey Annette! Just confirming we're still good for 31/1?

**Comment by apalski** [comment]
@tcn33 Hi Toby, yes I'm good for that :)
