### ISSUE TITLE
Dyslexia and Development

### ISSUE THREAD

**Issue by thrgamon** [rails-oceania/melbourne-ruby#90]
- What is dyslexia?
- How does it affect programming?
- Why Dyslexics can make excellent programmers.
- A few tips if you are dyslexic.
- A few tips you work with a dyslexic.

**Comment by fbvilela** [comment]
@thrgamon @tcn33 
here it is
https://youtu.be/MO3TJsQ_hQo

**Comment by tcn33** [comment]
@fbvilela thanks! 

Did the ones from September 27th record ok?
