### ISSUE TITLE
Cypress 101 - Testing in 2018 

### ISSUE THREAD

**Issue by Yogibeer2001** [rails-oceania/melbourne-ruby#91]
Cypress what is it?
what can it do?
why should I bother?
opinionated view on a new cool toy.
talk from lightning talk up to 30min

**Comment by tcn33** [comment]
@Yogibeer2001 sounds good! Are you available to give this talk in January? (31/1)

**Comment by Yogibeer2001** [comment]
Yes

**Comment by tcn33** [comment]
@Yogibeer2001 just confirming we're still good for 31/1?

**Comment by Yogibeer2001** [comment]
Yep all good and ready
