### ISSUE TITLE
Smaller is always better

### ISSUE THREAD

**Issue by philnash** [rails-oceania/melbourne-ruby#92]
Hello :wave: Just wanted to propose a talk for an upcoming meetup. What do you think?

---

Gzipping content has long been a best practice when serving text based files over the web. Turn on gzip compression in your web server, your users download smaller files quicker and everyone is happy, right?

That's what I thought as I went to tune my personal site over the holiday and I ended up writing 3 new gems and learning a whole bunch about the compression options available to us today. So join me on a journey to smaller and smaller files, discover how to tune your applications and find out how I ended up fighting a CDN over 1kB.

**Comment by tcn33** [comment]
@philnash looks great! How long are you thinking? Would you be available to do this talk on Feb 28?

**Comment by philnash** [comment]
I could totally do this on Feb 28th. How long are the meetup talks normally?

**Comment by tcn33** [comment]
20-30 minutes usually. (Shorter is good too as it will give more time for Q&A.)

We also may have a spot for January 31 if you're ready to go sooner.

**Comment by philnash** [comment]
I am not available on the 31st I'm afraid.

I can aim for 20 minutes to give plenty of extra time. Will warn you if I feel like it needs more time though!

**Comment by fbvilela** [comment]
Here we go
https://youtu.be/mmtwp8RPPAA
