### ISSUE TITLE
GraphQL in Rails

### ISSUE THREAD

**Issue by JeremyKirkham** [rails-oceania/melbourne-ruby#93]
Willing to do a quick talk: How I'm using GraphQL to serve a performant API to multiple front-ends (Angular 4 and iOS)

- Basic concepts
  - Difference between Rest and Graphql
  - Schema
  - Types
  - Mutations
  - Connections
  - Interfaces

- Overcoming issues
  - Debugging with GraphIQL

- Testing with rSpec (if there's time)

**Comment by tcn33** [comment]
@JeremyKirkham sounds good! Reckon you can cover that in 20 minutes?

**Comment by JeremyKirkham** [comment]
Yeah I’ll scope it to 15 minutes plus time for questions. March 28th is good.

**Comment by NamibiaLT** [comment]
Hi @JeremyKirkham , I'll be subbing in for Toby next RORO, 28th of March 2018. I would like to give you a short introduction prior to your talk. Would you be able to provide a short bio that reflects your interest in the topic you are presenting and the name of your talk. Also, please let me know whether you will be bringing your computer to present your slides. We will have all the equipment necessary to project your slides. I will be at Zendesk next Wednesday around 5:30pm to help speakers test out their slides if they choose to do so. If not, talks will begin on at 6:30pm sharp.

**Comment by JeremyKirkham** [comment]
@NamibiaLT I'll be bringing in my macbook with the preso loaded in google slides.

Name of presentation: GraphQL in Rails

Bio: 
With over 8 years of web development experience, I'm currently the lead software engineer for Equiem, as well as founder of Active PD.

My role has me working on multiple code repositories and technology stacks, ranging from Drupal/PHP, Ruby on Rails with Angular 4, Clojure, and Typescript. I am also heavily involved in the test and delivery pipelines for our projects, using tools and platforms such as Docker, CircleCI, Acquia, Heroku and AWS to get code shipped.

**Comment by fbvilela** [comment]
https://youtu.be/XUTpE4k-K_0

**Comment by fbvilela** [comment]
https://youtu.be/CA5feVQ3bJI
