### ISSUE TITLE
Demystifying Git

### ISSUE THREAD

**Issue by pauloancheta** [rails-oceania/melbourne-ruby#94]
Would love to give a talk on understanding how to use Git using LEGOs as an analogy.

In this talk, I will explain rebasing branches, different branching strategies, interactive rebase, re-writing history and responsible use of `git push -f`.

**Comment by tcn33** [comment]
@pauloancheta sounds great! How's March 28th?

**Comment by pauloancheta** [comment]
Do you have an earlier spot? Ill be in Bali at that time

**Comment by pauloancheta** [comment]
How much time do I have? Can I do 15min?

**Comment by tcn33** [comment]
@pauloancheta 15min with time for questions afterwards would be perfect.

**Comment by pauloancheta** [comment]
Yip, that's still ok. Thanks! :D
