### ISSUE TITLE
Presenting SVG graphs

### ISSUE THREAD

**Issue by Rhiana** [rails-oceania/melbourne-ruby#95]
Recently I wrote a Ruby presenter class that generated and SVG graph. I hadn't done that before and learnt a lot along the way so wanted to share the process.
This would be 20-30mins I think and at a fairly beginner to mid level.

For more details here is a blog post I wrote about it: [Presenting SVG graphs](https://reinteractive.com/posts/349-presenting-svg-graphs)

**Comment by tcn33** [comment]
@Rhiana sounds good! How's March 28th?

**Comment by Rhiana** [comment]
Can do, thanks @tcn33

**Comment by StaphSynth** [comment]
Awesome!

**Comment by Rhiana** [comment]
Hi @NamibiaLT 
No worries, my slides will be online so either way. I generally bring my own laptop with a backup though just in case. Would a windows or mac machine be easier with the set up there?

In terms of bio/intro something like:
> Rhiana currently works as a front-end Ruby on Rails Developer at reinteractive. Coming from a background in education and psychology, she's given talks here in the past on making the web accessible for people with disabilities. 
Today her talk is on another side of psychology, which is making graphs to show off all the data you just collected, but, thankfully, using Ruby on Rails. Here is Rhiana on "Presenting SVG graphs"

**Comment by NamibiaLT** [comment]
Hi @Rhiana! Either type of computer should be fine. Backups are always a good idea though. Also, how do I pronounce your name? Please let me know when you see me tomorrow :-)

**Comment by fbvilela** [comment]
https://www.youtube.com/watch?v=dDrdH_0BKLc
