### ISSUE TITLE
Putting your classes on a diet

### ISSUE THREAD

**Issue by HashNotAdam** [rails-oceania/melbourne-ruby#96]
Early in the lifecycle of a developer, it is common to fill out methods with every step needed to achieve a task leading to fat methods that are difficult to read, difficult to test, and near impossible to debug.

I plan to publicly shame myself by exposing a fat, controller method from the first Ruby code I every wrote and consider a few of different ways it could be broken into small, testable methods in classes that have only one concern.

Goal would be to keep the speaking time to 20 minutes.
Would need to be in the March meetup or I'll have to postpone for 6 months or so while overseas.

**Comment by HashNotAdam** [comment]
I guess this one will have to wait until I'm back from holiday. Just imagine how good it will be with 6 months to prepare 😆

**Comment by tcn33** [comment]
@HashNotAdam sorry about that, we had three talks lined up for March already. Looking forward to it in September though 😂

**Comment by HashNotAdam** [comment]
That's cool @tcn33, I only submitted it because you told me there was room but I still love you 😉
I'm quite certain is it a topic that won't age in the next 6 months. 👍
