### ISSUE TITLE
Web Scraping: How not to do it

### ISSUE THREAD

**Issue by Lewington-pitsos** [rails-oceania/melbourne-ruby#98]
## Who even likes API's anyway?  

They're almost always outdated and poorly maintained, and the Docs are only ever borderline legible *if* that. Most importantly though: *they never let you do anything cool*. It's all rate-limits and access restrictions. Phooey I say! If you really want to get your paws on all that sweet sweet data you've been eyeing down there's no better tool than the universal API: HTTP. 

This presentation covers what I learned over the last few months of trying and perpetually failing to git good at web scraping with Ruby. I'll be honest, I still have no idea what I'm doing, but if you're new to web scraping then hey, I might just save you a few months. 

### Talking points

1. Basics: how to Scrape with Net:HTTP
2. Capybara: how not to scrape (and the miracle of logging)
3. Headless vs Headful browsers: when and why
4. Storing Data: And why it's incredibly important
5. The Last Resort (or How I Learned to Stop Worrying and Love the Constant Errors)

Overall I see this going for about 25 intense minutes. If you think this could be fun, let me know. I would ideally like to do this talk at the march meetup (while everything's still fresh) if you have space, but whenever is cool really.

**Comment by Lewington-pitsos** [comment]
I have a rough draught of the presentation up and running [Here](https://github.com/Lewington-pitsos/web_scraping_presentation), but I was wondering: does anybody know when and/or how do we find out if and when we'll be presenting?

Cheers.

**Comment by tcn33** [comment]
@Lewington-pitsos how about April 25th? (Though I've just worked out that's Anzac Day so we're working out what that means for scheduling.)

**Comment by Lewington-pitsos** [comment]
April 25th (or like days around then) sounds great, plenty of time to test everything properly.

**Comment by tcn33** [comment]
@Lewington-pitsos we've moved to April 24. Still good?

**Comment by Lewington-pitsos** [comment]
Yes most certainly is, cheers for the update.

**Comment by Lewington-pitsos** [comment]
Hey, just letting you know that ill be running a tad late, but ill still be there in time to present! Cheers.

**Comment by Lewington-pitsos** [comment]
Hey ho, just confirming, is it still ok for me to do the presentation at next month's meetup? This time I'll test it on the laptop beforehand haha.

**Comment by tcn33** [comment]
@lewington-pitsos ping!

**Comment by Lewington-pitsos** [comment]
Shucks, sorry I swear I checked this like 3 days ago. Yes, we are ago on the presentation. AND it;s working on my laptop so unless there's no internet I'm good to go.
