### ISSUE TITLE
Intro to Docker

### ISSUE THREAD

**Issue by MelissaKaulfuss** [rails-oceania/melbourne-ruby#99]
10-15 minute talk.

Beginner-ish level talk just covering the basics of:

- what Virtual Machines are how they compare to Containers.
- Basics of Containers and Docker.

Doesn't go into the, how to get Docker up and running because I haven't really mastered that yet 😂

**Comment by tcn33** [comment]
@MelissaKaulfuss May 30th?

**Comment by MelissaKaulfuss** [comment]
Close to railscamp but sure, sounds fine @tcn33

**Comment by tcn33** [comment]
@MelissaKaulfuss I'll be your audience if you want to practice at camp 😋

**Comment by VanessaNimmo** [comment]
Closing this issue as @MelissaKaulfuss can no longer make RORO 😢
